
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/shridarpatil/whatomate/internal/handlers"


	_xtest "github.com/shridarpatil/whatomate/internal/handlers_test"

)

var tests = []testing.InternalTest{

	{"TestGetWhatsAppAccountCached_CacheMissPopulatesCache", _test.TestGetWhatsAppAccountCached_CacheMissPopulatesCache},

	{"TestGetWhatsAppAccountCached_CacheHitSkipsDB", _test.TestGetWhatsAppAccountCached_CacheHitSkipsDB},

	{"TestGetWhatsAppAccountCached_MatchesByJID", _test.TestGetWhatsAppAccountCached_MatchesByJID},

	{"TestGetWhatsAppAccountCached_NotFoundReturnsError", _test.TestGetWhatsAppAccountCached_NotFoundReturnsError},

	{"TestInvalidateWhatsAppAccountCache_DeletesKey", _test.TestInvalidateWhatsAppAccountCache_DeletesKey},

	{"TestDecryptAccountSecrets_DecryptsEncryptedValues", _test.TestDecryptAccountSecrets_DecryptsEncryptedValues},

	{"TestDecryptAccountSecrets_LeavesLegacyPlaintextUnchanged", _test.TestDecryptAccountSecrets_LeavesLegacyPlaintextUnchanged},

	{"TestGetWebhooksCached_OnlyActiveAndOrgScoped", _test.TestGetWebhooksCached_OnlyActiveAndOrgScoped},

	{"TestGetWebhooksCached_CacheHitSkipsDB", _test.TestGetWebhooksCached_CacheHitSkipsDB},

	{"TestInvalidateWebhooksCache_DeletesKey", _test.TestInvalidateWebhooksCache_DeletesKey},

	{"TestGetSLAEnabledSettingsCached_OnlySLAEnabledRows", _test.TestGetSLAEnabledSettingsCached_OnlySLAEnabledRows},

	{"TestInvalidateSLASettingsCache_DeletesKey", _test.TestInvalidateSLASettingsCache_DeletesKey},

	{"TestDeleteKeysByPattern_RemovesAllMatchingKeys", _test.TestDeleteKeysByPattern_RemovesAllMatchingKeys},

	{"TestInvalidateChatbotFlowsCache_DeletesKey", _test.TestInvalidateChatbotFlowsCache_DeletesKey},

	{"TestInvalidateChatbotSettingsCache_DeletesAllAccountVariants", _test.TestInvalidateChatbotSettingsCache_DeletesAllAccountVariants},

	{"TestParseCallAutoRejectSettings", _test.TestParseCallAutoRejectSettings},

	{"TestProcessGowaCallOffer_RejectsAndSendsMessage", _test.TestProcessGowaCallOffer_RejectsAndSendsMessage},

	{"TestProcessGowaCallOffer_DisabledDoesNothing", _test.TestProcessGowaCallOffer_DisabledDoesNothing},

	{"TestProcessGowaCallOffer_EmptyMessageRejectsSilently", _test.TestProcessGowaCallOffer_EmptyMessageRejectsSilently},

	{"TestProcessGowaCallOffer_RejectFailureSkipsMessage", _test.TestProcessGowaCallOffer_RejectFailureSkipsMessage},

	{"TestProcessGowaCallOffer_MalformedPayloadIgnored", _test.TestProcessGowaCallOffer_MalformedPayloadIgnored},

	{"TestEnsureCallOfferSubscription", _test.TestEnsureCallOfferSubscription},

	{"TestNormalizeRecipientPhone", _test.TestNormalizeRecipientPhone},

	{"TestParseRatingReply", _test.TestParseRatingReply},

	{"TestNormalizeRatingDigits", _test.TestNormalizeRatingDigits},

	{"TestParseCloseRatingSettings", _test.TestParseCloseRatingSettings},

	{"TestStepsToGraph_EmptyReturnsNil", _test.TestStepsToGraph_EmptyReturnsNil},

	{"TestStepsToGraph_TextStepProducesMessageNode", _test.TestStepsToGraph_TextStepProducesMessageNode},

	{"TestStepsToGraph_TextStepWithStoreAsBecomesPrompt", _test.TestStepsToGraph_TextStepWithStoreAsBecomesPrompt},

	{"TestStepsToGraph_ButtonsStepEmitsPerButtonEdges", _test.TestStepsToGraph_ButtonsStepEmitsPerButtonEdges},

	{"TestStepsToGraph_ApiFetchToApiCall", _test.TestStepsToGraph_ApiFetchToApiCall},

	{"TestStepsToGraph_WhatsAppFlowFieldRename", _test.TestStepsToGraph_WhatsAppFlowFieldRename},

	{"TestStepsToGraph_TransferIsTerminal", _test.TestStepsToGraph_TransferIsTerminal},

	{"TestStepsToGraph_TimingEdgesUseInHoursOutOfHours", _test.TestStepsToGraph_TimingEdgesUseInHoursOutOfHours},

	{"TestStepsToGraph_ConditionExpressionPassthrough", _test.TestStepsToGraph_ConditionExpressionPassthrough},

	{"TestStepsToGraph_GotoFlowTerminalWithFlowID", _test.TestStepsToGraph_GotoFlowTerminalWithFlowID},

	{"TestStepsToGraph_OrderingFollowsStepOrder", _test.TestStepsToGraph_OrderingFollowsStepOrder},

	{"TestStepsToGraph_CanvasPositionsApplied", _test.TestStepsToGraph_CanvasPositionsApplied},

	{"TestBackfillChatbotFlowGraph_FillsNullGraphsAndLeavesOthersAlone", _test.TestBackfillChatbotFlowGraph_FillsNullGraphsAndLeavesOthersAlone},

	{"TestRunChatGraph_GoldenPath", _test.TestRunChatGraph_GoldenPath},

	{"TestRunChatGraph_ButtonsStoreAs", _test.TestRunChatGraph_ButtonsStoreAs},

	{"TestRunChatGraph_ButtonsRePromptOnText", _test.TestRunChatGraph_ButtonsRePromptOnText},

	{"TestRunChatGraph_UnknownButtonEndsFlow", _test.TestRunChatGraph_UnknownButtonEndsFlow},

	{"TestParseChatGraph_InvalidGraph", _test.TestParseChatGraph_InvalidGraph},

	{"TestRunChatGraph_RunawayCycle", _test.TestRunChatGraph_RunawayCycle},

	{"TestRunChatGraph_Prompt_HappyPath", _test.TestRunChatGraph_Prompt_HappyPath},

	{"TestRunChatGraph_Prompt_RetryOnInvalid", _test.TestRunChatGraph_Prompt_RetryOnInvalid},

	{"TestRunChatGraph_Prompt_MaxRetriesRoutesToEdge", _test.TestRunChatGraph_Prompt_MaxRetriesRoutesToEdge},

	{"TestRunChatGraph_APICall_MessageTemplateSendsAfter2xx", _test.TestRunChatGraph_APICall_MessageTemplateSendsAfter2xx},

	{"TestRunChatGraph_APICall_2xxRoutesAndMapsResponse", _test.TestRunChatGraph_APICall_2xxRoutesAndMapsResponse},

	{"TestRunChatGraph_APICall_Non2xxRoutesToErrorBranch", _test.TestRunChatGraph_APICall_Non2xxRoutesToErrorBranch},

	{"TestRunChatGraph_APICall_NetworkErrorRoutesNon2xx", _test.TestRunChatGraph_APICall_NetworkErrorRoutesNon2xx},

	{"TestRunChatGraph_Condition_ExpressionAndOr", _test.TestRunChatGraph_Condition_ExpressionAndOr},

	{"TestRunChatGraph_Condition_ExpressionNot", _test.TestRunChatGraph_Condition_ExpressionNot},

	{"TestRunChatGraph_Condition_ExpressionMissingVariableIsFalse", _test.TestRunChatGraph_Condition_ExpressionMissingVariableIsFalse},

	{"TestRunChatGraph_Condition_ExpressionSyntaxErrorIsFalse", _test.TestRunChatGraph_Condition_ExpressionSyntaxErrorIsFalse},

	{"TestRunChatGraph_Condition_ExpressionContainsString", _test.TestRunChatGraph_Condition_ExpressionContainsString},

	{"TestEvaluateTimingSchedule", _test.TestEvaluateTimingSchedule},

	{"TestRunChatGraph_Timing_RoutesByCurrentTime", _test.TestRunChatGraph_Timing_RoutesByCurrentTime},

	{"TestRunChatGraph_SetVariable_Constant", _test.TestRunChatGraph_SetVariable_Constant},

	{"TestRunChatGraph_SetVariable_TemplateReferencesExisting", _test.TestRunChatGraph_SetVariable_TemplateReferencesExisting},

	{"TestRunChatGraph_SetVariable_MultipleAtOnce", _test.TestRunChatGraph_SetVariable_MultipleAtOnce},

	{"TestRunChatGraph_SetVariable_EmptyConfigNoOp", _test.TestRunChatGraph_SetVariable_EmptyConfigNoOp},

	{"TestRunChatGraph_SetVariable_NonStringStoredVerbatim", _test.TestRunChatGraph_SetVariable_NonStringStoredVerbatim},

	{"TestRunChatGraph_AIResponse_DisabledFallsThrough", _test.TestRunChatGraph_AIResponse_DisabledFallsThrough},

	{"TestRunChatGraph_AIResponse_NoSettingsRowFallsThrough", _test.TestRunChatGraph_AIResponse_NoSettingsRowFallsThrough},

	{"TestRunChatGraph_AIResponse_MissingAPIKeyFallsThrough", _test.TestRunChatGraph_AIResponse_MissingAPIKeyFallsThrough},

	{"TestRunChatGraph_Transfer_ToQueueCompletesSession", _test.TestRunChatGraph_Transfer_ToQueueCompletesSession},

	{"TestRunChatGraph_Transfer_ToSpecificTeam", _test.TestRunChatGraph_Transfer_ToSpecificTeam},

	{"TestRunChatGraph_Transfer_GeneralStringRoutesToQueue", _test.TestRunChatGraph_Transfer_GeneralStringRoutesToQueue},

	{"TestRunChatGraph_Webhook_SuccessAdvances", _test.TestRunChatGraph_Webhook_SuccessAdvances},

	{"TestRunChatGraph_Webhook_Non2xxStillAdvances", _test.TestRunChatGraph_Webhook_Non2xxStillAdvances},

	{"TestRunChatGraph_Webhook_NetworkErrorStillAdvances", _test.TestRunChatGraph_Webhook_NetworkErrorStillAdvances},

	{"TestRunChatGraph_GotoFlow_JumpsAndRunsTarget", _test.TestRunChatGraph_GotoFlow_JumpsAndRunsTarget},

	{"TestRunChatGraph_GotoFlow_VariablesCarryForward", _test.TestRunChatGraph_GotoFlow_VariablesCarryForward},

	{"TestRunChatGraph_GotoFlow_DisabledTargetIsTerminal", _test.TestRunChatGraph_GotoFlow_DisabledTargetIsTerminal},

	{"TestRunChatGraph_GotoFlow_MissingFlowIDTerminates", _test.TestRunChatGraph_GotoFlow_MissingFlowIDTerminates},

	{"TestRunChatGraph_GotoFlow_CycleBoundedByMaxIterations", _test.TestRunChatGraph_GotoFlow_CycleBoundedByMaxIterations},

	{"TestRunChatGraph_Prompt_NoRegexAcceptsAnything", _test.TestRunChatGraph_Prompt_NoRegexAcceptsAnything},

	{"TestProcessIncomingMessage_NoChatbotSettingsRoutesToQueue", _test.TestProcessIncomingMessage_NoChatbotSettingsRoutesToQueue},

	{"TestMatchKeywordRules_ExactMatch", _test.TestMatchKeywordRules_ExactMatch},

	{"TestMatchKeywordRules_ExactMatch_CaseSensitive", _test.TestMatchKeywordRules_ExactMatch_CaseSensitive},

	{"TestMatchKeywordRules_ContainsMatch", _test.TestMatchKeywordRules_ContainsMatch},

	{"TestMatchKeywordRules_StartsWithMatch", _test.TestMatchKeywordRules_StartsWithMatch},

	{"TestMatchKeywordRules_RegexMatch", _test.TestMatchKeywordRules_RegexMatch},

	{"TestMatchKeywordRules_NoMatch", _test.TestMatchKeywordRules_NoMatch},

	{"TestMatchKeywordRules_Priority", _test.TestMatchKeywordRules_Priority},

	{"TestMatchKeywordRules_DisabledRuleIgnored", _test.TestMatchKeywordRules_DisabledRuleIgnored},

	{"TestMatchKeywordRules_TransferType", _test.TestMatchKeywordRules_TransferType},

	{"TestMatchKeywordRules_WithButtons", _test.TestMatchKeywordRules_WithButtons},

	{"TestGetOrCreateSession_NewSession", _test.TestGetOrCreateSession_NewSession},

	{"TestGetOrCreateSession_ExistingSession", _test.TestGetOrCreateSession_ExistingSession},

	{"TestGetOrCreateSession_ExpiredSession", _test.TestGetOrCreateSession_ExpiredSession},

	{"TestIsWithinBusinessHours_WithinHours", _test.TestIsWithinBusinessHours_WithinHours},

	{"TestIsWithinBusinessHours_OutsideHours", _test.TestIsWithinBusinessHours_OutsideHours},

	{"TestIsWithinBusinessHours_DayDisabled", _test.TestIsWithinBusinessHours_DayDisabled},

	{"TestIsWithinBusinessHours_NoMatchingDay", _test.TestIsWithinBusinessHours_NoMatchingDay},

	{"TestIsWithinBusinessHours_EmptyHours", _test.TestIsWithinBusinessHours_EmptyHours},

	{"TestExitFlow_UpdatesSession", _test.TestExitFlow_UpdatesSession},

	{"TestSaveIncomingMessage_TextMessage", _test.TestSaveIncomingMessage_TextMessage},

	{"TestSaveIncomingMessage_WithMedia", _test.TestSaveIncomingMessage_WithMedia},

	{"TestSaveIncomingMessage_WithReplyContext", _test.TestSaveIncomingMessage_WithReplyContext},

	{"TestSaveIncomingMessage_LongContent", _test.TestSaveIncomingMessage_LongContent},

	{"TestProcessTemplateSessionData_Basic", _test.TestProcessTemplateSessionData_Basic},

	{"TestProcessTemplateSessionData_NilData", _test.TestProcessTemplateSessionData_NilData},

	{"TestProcessTemplateSessionData_MissingVariable", _test.TestProcessTemplateSessionData_MissingVariable},

	{"TestLogSessionMessage", _test.TestLogSessionMessage},

	{"TestMatchFlowTrigger_Match", _test.TestMatchFlowTrigger_Match},

	{"TestProcessIncomingMessage_CrossAccountSameWamidKeepsBothCopies", _test.TestProcessIncomingMessage_CrossAccountSameWamidKeepsBothCopies},

	{"TestProcessIncomingMessage_SameAccountDuplicateStillSkipped", _test.TestProcessIncomingMessage_SameAccountDuplicateStillSkipped},

	{"TestProcessGowaOutgoingMessage_CrossAccountSameWamidKeepsBothCopies", _test.TestProcessGowaOutgoingMessage_CrossAccountSameWamidKeepsBothCopies},

	{"TestCrossAccountMirrorContactIDs", _test.TestCrossAccountMirrorContactIDs},

	{"TestProcessGowaOutgoingMessage_SameAccountEchoStillDeduped", _test.TestProcessGowaOutgoingMessage_SameAccountEchoStillDeduped},

	{"TestRebaseGowaQRLink", _test.TestRebaseGowaQRLink},

	{"TestProcessGowaOutgoingMessage_NewContactBecomesPending", _test.TestProcessGowaOutgoingMessage_NewContactBecomesPending},

	{"TestProcessGowaOutgoingMessage_StaleOpenUnassignedBecomesPending", _test.TestProcessGowaOutgoingMessage_StaleOpenUnassignedBecomesPending},

	{"TestProcessGowaOutgoingMessage_ClosedChatReopensPending", _test.TestProcessGowaOutgoingMessage_ClosedChatReopensPending},

	{"TestProcessGowaOutgoingMessage_AssignedOpenUntouched", _test.TestProcessGowaOutgoingMessage_AssignedOpenUntouched},

	{"TestParsePathUUID_Valid", _test.TestParsePathUUID_Valid},

	{"TestParsePathUUID_Invalid", _test.TestParsePathUUID_Invalid},

	{"TestParsePathUUID_Missing", _test.TestParsePathUUID_Missing},

	{"TestParsePagination_Defaults", _test.TestParsePagination_Defaults},

	{"TestParsePagination_CustomValues", _test.TestParsePagination_CustomValues},

	{"TestParsePagination_MaxLimitCapping", _test.TestParsePagination_MaxLimitCapping},

	{"TestParsePagination_ZeroPageDefaults", _test.TestParsePagination_ZeroPageDefaults},

	{"TestParsePagination_NegativeValues", _test.TestParsePagination_NegativeValues},

	{"TestParsePaginationWithDefaults_CustomDefaultAndMax", _test.TestParsePaginationWithDefaults_CustomDefaultAndMax},

	{"TestParsePaginationWithDefaults_LimitExceedsMax", _test.TestParsePaginationWithDefaults_LimitExceedsMax},

	{"TestParseDateParam_Valid", _test.TestParseDateParam_Valid},

	{"TestParseDateParam_Invalid", _test.TestParseDateParam_Invalid},

	{"TestParseDateParam_Missing", _test.TestParseDateParam_Missing},

	{"TestParseDateParam_WrongFormat", _test.TestParseDateParam_WrongFormat},

	{"TestEndOfDay", _test.TestEndOfDay},

	{"TestFindByIDAndOrg_Found", _test.TestFindByIDAndOrg_Found},

	{"TestFindByIDAndOrg_NotFound", _test.TestFindByIDAndOrg_NotFound},

	{"TestFindByIDAndOrg_CrossOrgIsolation", _test.TestFindByIDAndOrg_CrossOrgIsolation},

	{"TestMaskPhoneNumber", _test.TestMaskPhoneNumber},

	{"TestLooksLikePhoneNumber", _test.TestLooksLikePhoneNumber},

	{"TestMaskIfPhoneNumber", _test.TestMaskIfPhoneNumber},

	{"TestParseDateRange_Valid", _test.TestParseDateRange_Valid},

	{"TestParseDateRange_InvalidStartDate", _test.TestParseDateRange_InvalidStartDate},

	{"TestParseDateRange_InvalidEndDate", _test.TestParseDateRange_InvalidEndDate},

	{"TestParseDateRange_WrongFormat", _test.TestParseDateRange_WrongFormat},

	{"TestParseDateRange_SameDay", _test.TestParseDateRange_SameDay},

	{"TestAgentRespondedSince_TrueWhenMessageAfterTimestamp", _test.TestAgentRespondedSince_TrueWhenMessageAfterTimestamp},

	{"TestAgentRespondedSince_FalseWhenNoMessages", _test.TestAgentRespondedSince_FalseWhenNoMessages},

	{"TestAgentRespondedSince_FalseWhenNoAgent", _test.TestAgentRespondedSince_FalseWhenNoAgent},

	{"TestAgentRespondedSince_FalseWhenMessageBeforeTimestamp", _test.TestAgentRespondedSince_FalseWhenMessageBeforeTimestamp},

	{"TestSLAAutoCloseSkippedWhenAgentActive", _test.TestSLAAutoCloseSkippedWhenAgentActive},

	{"TestSLAAutoCloseFiresWhenNoAgentResponse", _test.TestSLAAutoCloseFiresWhenNoAgentResponse},

	{"TestSLAEscalationSkippedWhenAgentActive", _test.TestSLAEscalationSkippedWhenAgentActive},

	{"TestSLAEscalationFiresWhenNoAgentResponse", _test.TestSLAEscalationFiresWhenNoAgentResponse},

	{"TestProcessTemplate_EmptyTemplate", _test.TestProcessTemplate_EmptyTemplate},

	{"TestProcessTemplate_NoPlaceholders", _test.TestProcessTemplate_NoPlaceholders},

	{"TestProcessTemplate_VariablesOnly", _test.TestProcessTemplate_VariablesOnly},

	{"TestProcessTemplate_LoopsOnly", _test.TestProcessTemplate_LoopsOnly},

	{"TestProcessTemplate_ConditionalsOnly", _test.TestProcessTemplate_ConditionalsOnly},

	{"TestProcessTemplate_Mixed", _test.TestProcessTemplate_Mixed},

	{"TestProcessTemplate_NilData", _test.TestProcessTemplate_NilData},

	{"TestProcessTemplate_NestedLoopsWithConditionals", _test.TestProcessTemplate_NestedLoopsWithConditionals},

	{"TestProcessForLoops_EmptyArray", _test.TestProcessForLoops_EmptyArray},

	{"TestProcessForLoops_SingleItem", _test.TestProcessForLoops_SingleItem},

	{"TestProcessForLoops_MultipleItems", _test.TestProcessForLoops_MultipleItems},

	{"TestProcessForLoops_NestedObjectAccess", _test.TestProcessForLoops_NestedObjectAccess},

	{"TestProcessForLoops_MissingArray", _test.TestProcessForLoops_MissingArray},

	{"TestProcessForLoops_IndexVariable", _test.TestProcessForLoops_IndexVariable},

	{"TestProcessForLoops_MapSlice", _test.TestProcessForLoops_MapSlice},

	{"TestProcessForLoops_NonArrayValue", _test.TestProcessForLoops_NonArrayValue},

	{"TestProcessForLoops_NestedPath", _test.TestProcessForLoops_NestedPath},

	{"TestProcessConditionals_TruthyCondition", _test.TestProcessConditionals_TruthyCondition},

	{"TestProcessConditionals_FalsyCondition", _test.TestProcessConditionals_FalsyCondition},

	{"TestProcessConditionals_ElseBranch", _test.TestProcessConditionals_ElseBranch},

	{"TestProcessConditionals_ElseBranchTrue", _test.TestProcessConditionals_ElseBranchTrue},

	{"TestProcessConditionals_NumericGreaterThan", _test.TestProcessConditionals_NumericGreaterThan},

	{"TestProcessConditionals_NumericLessThan", _test.TestProcessConditionals_NumericLessThan},

	{"TestProcessConditionals_StringEquality", _test.TestProcessConditionals_StringEquality},

	{"TestProcessConditionals_StringInequality", _test.TestProcessConditionals_StringInequality},

	{"TestProcessConditionals_MissingVariable", _test.TestProcessConditionals_MissingVariable},

	{"TestProcessConditionals_NestedPath", _test.TestProcessConditionals_NestedPath},

	{"TestProcessConditionals_GreaterThanOrEqual", _test.TestProcessConditionals_GreaterThanOrEqual},

	{"TestProcessConditionals_LessThanOrEqual", _test.TestProcessConditionals_LessThanOrEqual},

	{"TestProcessVariables_Simple", _test.TestProcessVariables_Simple},

	{"TestProcessVariables_NestedPath", _test.TestProcessVariables_NestedPath},

	{"TestProcessVariables_ArrayIndex", _test.TestProcessVariables_ArrayIndex},

	{"TestProcessVariables_MissingVariable", _test.TestProcessVariables_MissingVariable},

	{"TestProcessVariables_MultipleVariables", _test.TestProcessVariables_MultipleVariables},

	{"TestProcessVariables_NoPlaceholders", _test.TestProcessVariables_NoPlaceholders},

	{"TestGetNestedValue_SimpleKey", _test.TestGetNestedValue_SimpleKey},

	{"TestGetNestedValue_NestedKey", _test.TestGetNestedValue_NestedKey},

	{"TestGetNestedValue_ArrayIndex", _test.TestGetNestedValue_ArrayIndex},

	{"TestGetNestedValue_ArrayOutOfBounds", _test.TestGetNestedValue_ArrayOutOfBounds},

	{"TestGetNestedValue_MissingKey", _test.TestGetNestedValue_MissingKey},

	{"TestGetNestedValue_NilData", _test.TestGetNestedValue_NilData},

	{"TestGetNestedValue_EmptyPath", _test.TestGetNestedValue_EmptyPath},

	{"TestGetNestedValue_DeepNestedWithArray", _test.TestGetNestedValue_DeepNestedWithArray},

	{"TestGetNestedValue_MapSliceIndex", _test.TestGetNestedValue_MapSliceIndex},

	{"TestSplitPath_Simple", _test.TestSplitPath_Simple},

	{"TestSplitPath_DotNotation", _test.TestSplitPath_DotNotation},

	{"TestSplitPath_BracketNotation", _test.TestSplitPath_BracketNotation},

	{"TestSplitPath_MixedNotation", _test.TestSplitPath_MixedNotation},

	{"TestSplitPath_Empty", _test.TestSplitPath_Empty},

	{"TestEvaluateCondition_TruthyVariable", _test.TestEvaluateCondition_TruthyVariable},

	{"TestEvaluateCondition_FalsyVariable", _test.TestEvaluateCondition_FalsyVariable},

	{"TestEvaluateCondition_MissingVariable", _test.TestEvaluateCondition_MissingVariable},

	{"TestEvaluateCondition_EqualOperator", _test.TestEvaluateCondition_EqualOperator},

	{"TestEvaluateCondition_NotEqualOperator", _test.TestEvaluateCondition_NotEqualOperator},

	{"TestEvaluateCondition_GreaterThan", _test.TestEvaluateCondition_GreaterThan},

	{"TestEvaluateCondition_LessThan", _test.TestEvaluateCondition_LessThan},

	{"TestEvaluateCondition_GreaterThanOrEqual", _test.TestEvaluateCondition_GreaterThanOrEqual},

	{"TestEvaluateCondition_LessThanOrEqual", _test.TestEvaluateCondition_LessThanOrEqual},

	{"TestEvaluateCondition_DoubleQuotes", _test.TestEvaluateCondition_DoubleQuotes},

	{"TestEvaluateCondition_NestedPath", _test.TestEvaluateCondition_NestedPath},

	{"TestEvaluateCondition_EmptyCondition", _test.TestEvaluateCondition_EmptyCondition},

	{"TestIsTruthy", _test.TestIsTruthy},

	{"TestCompareEqual", _test.TestCompareEqual},

	{"TestCompareNumeric", _test.TestCompareNumeric},

	{"TestFormatValue", _test.TestFormatValue},

	{"TestCopyMap_ShallowCopy", _test.TestCopyMap_ShallowCopy},

	{"TestCopyMap_Empty", _test.TestCopyMap_Empty},

	{"TestCopyMap_NilSafe", _test.TestCopyMap_NilSafe},

	{"TestExtractResponseMapping_SimpleKey", _test.TestExtractResponseMapping_SimpleKey},

	{"TestExtractResponseMapping_NestedPath", _test.TestExtractResponseMapping_NestedPath},

	{"TestExtractResponseMapping_MissingKey", _test.TestExtractResponseMapping_MissingKey},

	{"TestExtractResponseMapping_EmptyMapping", _test.TestExtractResponseMapping_EmptyMapping},

	{"TestExtractResponseMapping_PartialMatch", _test.TestExtractResponseMapping_PartialMatch},

	{"TestApp_ListAccounts_Success", _xtest.TestApp_ListAccounts_Success},

	{"TestApp_ListAccounts_Empty", _xtest.TestApp_ListAccounts_Empty},

	{"TestApp_ListAccounts_Unauthorized", _xtest.TestApp_ListAccounts_Unauthorized},

	{"TestApp_ListAccounts_OrgIsolation", _xtest.TestApp_ListAccounts_OrgIsolation},

	{"TestApp_CreateAccount_Success", _xtest.TestApp_CreateAccount_Success},

	{"TestApp_CreateAccount_WithOptionalFields", _xtest.TestApp_CreateAccount_WithOptionalFields},

	{"TestApp_CreateAccount_ValidationErrors", _xtest.TestApp_CreateAccount_ValidationErrors},

	{"TestApp_CreateAccount_Unauthorized", _xtest.TestApp_CreateAccount_Unauthorized},

	{"TestApp_GetAccount_Success", _xtest.TestApp_GetAccount_Success},

	{"TestApp_GetAccount_NotFound", _xtest.TestApp_GetAccount_NotFound},

	{"TestApp_GetAccount_InvalidID", _xtest.TestApp_GetAccount_InvalidID},

	{"TestApp_GetAccount_CrossOrgIsolation", _xtest.TestApp_GetAccount_CrossOrgIsolation},

	{"TestApp_UpdateAccount_Success", _xtest.TestApp_UpdateAccount_Success},

	{"TestApp_UpdateAccount_PartialUpdate", _xtest.TestApp_UpdateAccount_PartialUpdate},

	{"TestApp_UpdateAccount_NotFound", _xtest.TestApp_UpdateAccount_NotFound},

	{"TestApp_UpdateAccount_InvalidID", _xtest.TestApp_UpdateAccount_InvalidID},

	{"TestApp_DeleteAccount_Success", _xtest.TestApp_DeleteAccount_Success},

	{"TestApp_DeleteAccount_NotFound", _xtest.TestApp_DeleteAccount_NotFound},

	{"TestApp_DeleteAccount_InvalidID", _xtest.TestApp_DeleteAccount_InvalidID},

	{"TestApp_DeleteAccount_CrossOrgIsolation", _xtest.TestApp_DeleteAccount_CrossOrgIsolation},

	{"TestApp_CreateAccount_WebhookSecretEncryptedAtRest", _xtest.TestApp_CreateAccount_WebhookSecretEncryptedAtRest},

	{"TestApp_CreateAccount_WebhookSecretAutoGeneratedWhenEmpty", _xtest.TestApp_CreateAccount_WebhookSecretAutoGeneratedWhenEmpty},

	{"TestApp_CreateAccount_DefaultIncomingFlipsExisting", _xtest.TestApp_CreateAccount_DefaultIncomingFlipsExisting},

	{"TestApp_ListAgentTransfers_Success", _xtest.TestApp_ListAgentTransfers_Success},

	{"TestApp_ListAgentTransfers_FilterByStatus", _xtest.TestApp_ListAgentTransfers_FilterByStatus},

	{"TestApp_ListAgentTransfers_AgentRoleFiltering", _xtest.TestApp_ListAgentTransfers_AgentRoleFiltering},

	{"TestApp_ListAgentTransfers_Pagination", _xtest.TestApp_ListAgentTransfers_Pagination},

	{"TestApp_CreateAgentTransfer_Success", _xtest.TestApp_CreateAgentTransfer_Success},

	{"TestApp_CreateAgentTransfer_WithAgent", _xtest.TestApp_CreateAgentTransfer_WithAgent},

	{"TestApp_CreateAgentTransfer_ContactNotFound", _xtest.TestApp_CreateAgentTransfer_ContactNotFound},

	{"TestApp_CreateAgentTransfer_DuplicateTransfer", _xtest.TestApp_CreateAgentTransfer_DuplicateTransfer},

	{"TestApp_CreateAgentTransfer_MissingContactID", _xtest.TestApp_CreateAgentTransfer_MissingContactID},

	{"TestApp_CreateAgentTransfer_AgentUnavailable", _xtest.TestApp_CreateAgentTransfer_AgentUnavailable},

	{"TestApp_ResumeFromTransfer_Success", _xtest.TestApp_ResumeFromTransfer_Success},

	{"TestApp_ResumeFromTransfer_NotFound", _xtest.TestApp_ResumeFromTransfer_NotFound},

	{"TestApp_ResumeFromTransfer_NotActive", _xtest.TestApp_ResumeFromTransfer_NotActive},

	{"TestApp_AssignAgentTransfer_Success", _xtest.TestApp_AssignAgentTransfer_Success},

	{"TestApp_AssignAgentTransfer_AgentSelfAssign", _xtest.TestApp_AssignAgentTransfer_AgentSelfAssign},

	{"TestApp_AssignAgentTransfer_AgentCannotAssignToOthers", _xtest.TestApp_AssignAgentTransfer_AgentCannotAssignToOthers},

	{"TestApp_AssignAgentTransfer_NotActive", _xtest.TestApp_AssignAgentTransfer_NotActive},

	{"TestApp_PickNextTransfer_Success", _xtest.TestApp_PickNextTransfer_Success},

	{"TestApp_PickNextTransfer_EmptyQueue", _xtest.TestApp_PickNextTransfer_EmptyQueue},

	{"TestApp_PickNextTransfer_FIFO", _xtest.TestApp_PickNextTransfer_FIFO},

	{"TestApp_PickNextTransfer_TeamFiltering", _xtest.TestApp_PickNextTransfer_TeamFiltering},

	{"TestApp_AgentTransfers_CrossOrgIsolation", _xtest.TestApp_AgentTransfers_CrossOrgIsolation},

	{"TestApp_ReturnAgentTransfersToQueue", _xtest.TestApp_ReturnAgentTransfersToQueue},

	{"TestApp_PickNextTransfer_AssignToSameAgentTrue_PinsRelationshipManager", _xtest.TestApp_PickNextTransfer_AssignToSameAgentTrue_PinsRelationshipManager},

	{"TestApp_PickNextTransfer_AssignToSameAgentFalse_LeavesContactUnassigned", _xtest.TestApp_PickNextTransfer_AssignToSameAgentFalse_LeavesContactUnassigned},

	{"TestApp_PickNextTransfer_DoesNotOverwriteExistingRelationshipManager", _xtest.TestApp_PickNextTransfer_DoesNotOverwriteExistingRelationshipManager},

	{"TestApp_ReturnAgentTransfersToQueue_DoesNotClearManualAssignment", _xtest.TestApp_ReturnAgentTransfersToQueue_DoesNotClearManualAssignment},

	{"TestApp_ReturnAgentTransfersToQueue_ClearsAssignmentWhenItPointsAtAgent", _xtest.TestApp_ReturnAgentTransfersToQueue_ClearsAssignmentWhenItPointsAtAgent},

	{"TestApp_GetAgentAnalytics_Success", _xtest.TestApp_GetAgentAnalytics_Success},

	{"TestApp_GetAgentAnalytics_EmptyData", _xtest.TestApp_GetAgentAnalytics_EmptyData},

	{"TestApp_GetAgentAnalytics_Unauthorized", _xtest.TestApp_GetAgentAnalytics_Unauthorized},

	{"TestApp_GetAgentAnalytics_AgentSeesOwnStats", _xtest.TestApp_GetAgentAnalytics_AgentSeesOwnStats},

	{"TestApp_GetAgentAnalytics_ClosureRatings", _xtest.TestApp_GetAgentAnalytics_ClosureRatings},

	{"TestApp_GetAgentAnalytics_NoRatings", _xtest.TestApp_GetAgentAnalytics_NoRatings},

	{"TestApp_GetAPIKey_Success", _xtest.TestApp_GetAPIKey_Success},

	{"TestApp_GetAPIKey_NotFound", _xtest.TestApp_GetAPIKey_NotFound},

	{"TestApp_GetAPIKey_CrossOrgIsolation", _xtest.TestApp_GetAPIKey_CrossOrgIsolation},

	{"TestApp_GetAPIKey_InvalidID", _xtest.TestApp_GetAPIKey_InvalidID},

	{"TestApp_GetAPIKey_PermissionDenied", _xtest.TestApp_GetAPIKey_PermissionDenied},

	{"TestApp_UpdateAPIKey_TogglesIsActive", _xtest.TestApp_UpdateAPIKey_TogglesIsActive},

	{"TestApp_UpdateAPIKey_NilIsActiveLeavesUnchanged", _xtest.TestApp_UpdateAPIKey_NilIsActiveLeavesUnchanged},

	{"TestApp_UpdateAPIKey_NotFound", _xtest.TestApp_UpdateAPIKey_NotFound},

	{"TestApp_UpdateAPIKey_CrossOrgIsolation", _xtest.TestApp_UpdateAPIKey_CrossOrgIsolation},

	{"TestApp_UpdateAPIKey_PermissionDenied", _xtest.TestApp_UpdateAPIKey_PermissionDenied},

	{"TestApp_CreateAPIKey_EmptyNameRejected", _xtest.TestApp_CreateAPIKey_EmptyNameRejected},

	{"TestApp_CreateAPIKey_ExpiresAtParsedAndStored", _xtest.TestApp_CreateAPIKey_ExpiresAtParsedAndStored},

	{"TestApp_CreateAPIKey_InvalidExpiresAtFormat", _xtest.TestApp_CreateAPIKey_InvalidExpiresAtFormat},

	{"TestApp_CreateAPIKey_HashIsBcryptOfFullKey", _xtest.TestApp_CreateAPIKey_HashIsBcryptOfFullKey},

	{"TestApp_CreateAPIKey_PermissionDenied", _xtest.TestApp_CreateAPIKey_PermissionDenied},

	{"TestApp_ListAPIKeys_SearchFilter", _xtest.TestApp_ListAPIKeys_SearchFilter},

	{"TestApp_ListAPIKeys", _xtest.TestApp_ListAPIKeys},

	{"TestApp_CreateAPIKey", _xtest.TestApp_CreateAPIKey},

	{"TestApp_ListAPIKeys_CrossOrgIsolation", _xtest.TestApp_ListAPIKeys_CrossOrgIsolation},

	{"TestApp_ListAPIKeys_ResponseFields", _xtest.TestApp_ListAPIKeys_ResponseFields},

	{"TestApp_ListAPIKeys_ExcludesDeletedKeys", _xtest.TestApp_ListAPIKeys_ExcludesDeletedKeys},

	{"TestApp_CreateAPIKey_KeyFormat", _xtest.TestApp_CreateAPIKey_KeyFormat},

	{"TestApp_CreateAPIKey_UniqueKeys", _xtest.TestApp_CreateAPIKey_UniqueKeys},

	{"TestApp_CreateAPIKey_DatabasePersistence", _xtest.TestApp_CreateAPIKey_DatabasePersistence},

	{"TestApp_CreateAPIKey_InvalidJSONBody", _xtest.TestApp_CreateAPIKey_InvalidJSONBody},

	{"TestApp_DeleteAPIKey", _xtest.TestApp_DeleteAPIKey},

	{"TestApp_ListAuditLogs_Success", _xtest.TestApp_ListAuditLogs_Success},

	{"TestApp_ListAuditLogs_FilterByResourceType", _xtest.TestApp_ListAuditLogs_FilterByResourceType},

	{"TestApp_ListAuditLogs_FilterByResourceTypeMulti", _xtest.TestApp_ListAuditLogs_FilterByResourceTypeMulti},

	{"TestApp_ListAuditLogs_FilterByAction", _xtest.TestApp_ListAuditLogs_FilterByAction},

	{"TestApp_ListAuditLogs_DateRangeFilter", _xtest.TestApp_ListAuditLogs_DateRangeFilter},

	{"TestApp_ListAuditLogs_CrossOrgIsolation", _xtest.TestApp_ListAuditLogs_CrossOrgIsolation},

	{"TestApp_ListAuditLogs_PermissionDenied", _xtest.TestApp_ListAuditLogs_PermissionDenied},

	{"TestApp_GetAuditLog_Success", _xtest.TestApp_GetAuditLog_Success},

	{"TestApp_GetAuditLog_NotFound", _xtest.TestApp_GetAuditLog_NotFound},

	{"TestApp_GetAuditLog_CrossOrgIsolation", _xtest.TestApp_GetAuditLog_CrossOrgIsolation},

	{"TestApp_SwitchOrg_AccessTokenCarriesUserOrgRole", _xtest.TestApp_SwitchOrg_AccessTokenCarriesUserOrgRole},

	{"TestApp_SwitchOrg_InvalidJSON", _xtest.TestApp_SwitchOrg_InvalidJSON},

	{"TestApp_Logout_ClearsCookiesAndReturnsOK", _xtest.TestApp_Logout_ClearsCookiesAndReturnsOK},

	{"TestApp_Logout_RevokesRefreshTokenJTI", _xtest.TestApp_Logout_RevokesRefreshTokenJTI},

	{"TestApp_Logout_NoTokenStillSucceeds", _xtest.TestApp_Logout_NoTokenStillSucceeds},

	{"TestApp_Logout_GarbageRefreshTokenStillSucceeds", _xtest.TestApp_Logout_GarbageRefreshTokenStillSucceeds},

	{"TestApp_Logout_FromCookie", _xtest.TestApp_Logout_FromCookie},

	{"TestApp_GetWSToken_Success", _xtest.TestApp_GetWSToken_Success},

	{"TestApp_GetWSToken_MissingUserID", _xtest.TestApp_GetWSToken_MissingUserID},

	{"TestApp_GetWSToken_MissingOrgID", _xtest.TestApp_GetWSToken_MissingOrgID},

	{"TestApp_RefreshToken_RevokedJTI", _xtest.TestApp_RefreshToken_RevokedJTI},

	{"TestApp_RefreshToken_RotatesJTI_ReplayFails", _xtest.TestApp_RefreshToken_RotatesJTI_ReplayFails},

	{"TestApp_RefreshToken_FromCookie", _xtest.TestApp_RefreshToken_FromCookie},

	{"TestApp_Login_Success", _xtest.TestApp_Login_Success},

	{"TestApp_Login_WrongPassword", _xtest.TestApp_Login_WrongPassword},

	{"TestApp_Login_UserNotFound", _xtest.TestApp_Login_UserNotFound},

	{"TestApp_Login_InactiveUser", _xtest.TestApp_Login_InactiveUser},

	{"TestApp_Login_InvalidRequestBody", _xtest.TestApp_Login_InvalidRequestBody},

	{"TestApp_Login_UserWithRole", _xtest.TestApp_Login_UserWithRole},

	{"TestApp_Register_Success", _xtest.TestApp_Register_Success},

	{"TestApp_Register_EmailAlreadyExists_WrongPassword", _xtest.TestApp_Register_EmailAlreadyExists_WrongPassword},

	{"TestApp_Register_ExistingUser_JoinsNewOrg", _xtest.TestApp_Register_ExistingUser_JoinsNewOrg},

	{"TestApp_Register_InvalidRequestBody", _xtest.TestApp_Register_InvalidRequestBody},

	{"TestApp_RefreshToken_Success", _xtest.TestApp_RefreshToken_Success},

	{"TestApp_RefreshToken_Expired", _xtest.TestApp_RefreshToken_Expired},

	{"TestApp_RefreshToken_InvalidSignature", _xtest.TestApp_RefreshToken_InvalidSignature},

	{"TestApp_RefreshToken_UserNotFound", _xtest.TestApp_RefreshToken_UserNotFound},

	{"TestApp_RefreshToken_DisabledUser", _xtest.TestApp_RefreshToken_DisabledUser},

	{"TestApp_RefreshToken_MalformedToken", _xtest.TestApp_RefreshToken_MalformedToken},

	{"TestApp_RefreshToken_InvalidRequestBody", _xtest.TestApp_RefreshToken_InvalidRequestBody},

	{"TestApp_GeneratedTokensAreValid", _xtest.TestApp_GeneratedTokensAreValid},

	{"TestApp_GetCallAutoRejectSettings_Defaults", _xtest.TestApp_GetCallAutoRejectSettings_Defaults},

	{"TestApp_GetCallAutoRejectSettings_AccountOverrides", _xtest.TestApp_GetCallAutoRejectSettings_AccountOverrides},

	{"TestApp_GetCallAutoRejectSettings_Unauthorized", _xtest.TestApp_GetCallAutoRejectSettings_Unauthorized},

	{"TestApp_GetCallAutoRejectSettings_NotFound", _xtest.TestApp_GetCallAutoRejectSettings_NotFound},

	{"TestApp_UpdateCallAutoRejectSettings_Success", _xtest.TestApp_UpdateCallAutoRejectSettings_Success},

	{"TestApp_UpdateCallAutoRejectSettings_Unauthorized", _xtest.TestApp_UpdateCallAutoRejectSettings_Unauthorized},

	{"TestApp_UpdateCallAutoRejectSettings_NotFound", _xtest.TestApp_UpdateCallAutoRejectSettings_NotFound},

	{"TestApp_ListCampaigns_Success", _xtest.TestApp_ListCampaigns_Success},

	{"TestApp_ListCampaigns_FilterByStatus", _xtest.TestApp_ListCampaigns_FilterByStatus},

	{"TestApp_ListCampaigns_Unauthorized", _xtest.TestApp_ListCampaigns_Unauthorized},

	{"TestApp_CreateCampaign_Success", _xtest.TestApp_CreateCampaign_Success},

	{"TestApp_CreateCampaign_WithScheduledAt", _xtest.TestApp_CreateCampaign_WithScheduledAt},

	{"TestApp_CreateCampaign_InvalidTemplateID", _xtest.TestApp_CreateCampaign_InvalidTemplateID},

	{"TestApp_CreateCampaign_TemplateNotFound", _xtest.TestApp_CreateCampaign_TemplateNotFound},

	{"TestApp_CreateCampaign_AccountNotFound", _xtest.TestApp_CreateCampaign_AccountNotFound},

	{"TestApp_CreateCampaign_InvalidRequestBody", _xtest.TestApp_CreateCampaign_InvalidRequestBody},

	{"TestApp_GetCampaign_Success", _xtest.TestApp_GetCampaign_Success},

	{"TestApp_GetCampaign_NotFound", _xtest.TestApp_GetCampaign_NotFound},

	{"TestApp_GetCampaign_InvalidID", _xtest.TestApp_GetCampaign_InvalidID},

	{"TestApp_UpdateCampaign_Success", _xtest.TestApp_UpdateCampaign_Success},

	{"TestApp_UpdateCampaign_NotDraft", _xtest.TestApp_UpdateCampaign_NotDraft},

	{"TestApp_UpdateCampaign_NotFound", _xtest.TestApp_UpdateCampaign_NotFound},

	{"TestApp_DeleteCampaign_Success", _xtest.TestApp_DeleteCampaign_Success},

	{"TestApp_DeleteCampaign_WithRecipients", _xtest.TestApp_DeleteCampaign_WithRecipients},

	{"TestApp_DeleteCampaign_RunningCampaign", _xtest.TestApp_DeleteCampaign_RunningCampaign},

	{"TestApp_DeleteCampaign_NotFound", _xtest.TestApp_DeleteCampaign_NotFound},

	{"TestApp_StartCampaign_Success", _xtest.TestApp_StartCampaign_Success},

	{"TestApp_StartCampaign_NoPendingRecipients", _xtest.TestApp_StartCampaign_NoPendingRecipients},

	{"TestApp_StartCampaign_InvalidStatus", _xtest.TestApp_StartCampaign_InvalidStatus},

	{"TestApp_StartCampaign_CanResumePaused", _xtest.TestApp_StartCampaign_CanResumePaused},

	{"TestApp_PauseCampaign_Success", _xtest.TestApp_PauseCampaign_Success},

	{"TestApp_PauseCampaign_NotRunning", _xtest.TestApp_PauseCampaign_NotRunning},

	{"TestApp_CancelCampaign_Success", _xtest.TestApp_CancelCampaign_Success},

	{"TestApp_CancelCampaign_AlreadyFinished", _xtest.TestApp_CancelCampaign_AlreadyFinished},

	{"TestApp_ImportRecipients_Success", _xtest.TestApp_ImportRecipients_Success},

	{"TestApp_ImportRecipients_RejectsGroupsAndNewsletters", _xtest.TestApp_ImportRecipients_RejectsGroupsAndNewsletters},

	{"TestApp_ImportRecipients_AllInvalid", _xtest.TestApp_ImportRecipients_AllInvalid},

	{"TestApp_ImportRecipients_WithTemplateParams", _xtest.TestApp_ImportRecipients_WithTemplateParams},

	{"TestApp_ImportRecipients_WithHeaderParams", _xtest.TestApp_ImportRecipients_WithHeaderParams},

	{"TestApp_ImportRecipients_NotDraft", _xtest.TestApp_ImportRecipients_NotDraft},

	{"TestApp_GetCampaignRecipients_Success", _xtest.TestApp_GetCampaignRecipients_Success},

	{"TestApp_GetCampaignRecipients_CampaignNotFound", _xtest.TestApp_GetCampaignRecipients_CampaignNotFound},

	{"TestApp_RetryFailed_Success", _xtest.TestApp_RetryFailed_Success},

	{"TestApp_RetryFailed_NoFailedRecipients", _xtest.TestApp_RetryFailed_NoFailedRecipients},

	{"TestApp_RetryFailed_InvalidStatus", _xtest.TestApp_RetryFailed_InvalidStatus},

	{"TestApp_Campaign_CrossOrgIsolation", _xtest.TestApp_Campaign_CrossOrgIsolation},

	{"TestApp_ListCannedResponses", _xtest.TestApp_ListCannedResponses},

	{"TestApp_CreateCannedResponse", _xtest.TestApp_CreateCannedResponse},

	{"TestApp_GetCannedResponse", _xtest.TestApp_GetCannedResponse},

	{"TestApp_UpdateCannedResponse", _xtest.TestApp_UpdateCannedResponse},

	{"TestApp_DeleteCannedResponse", _xtest.TestApp_DeleteCannedResponse},

	{"TestApp_CreateCannedResponse_DuplicateShortcut", _xtest.TestApp_CreateCannedResponse_DuplicateShortcut},

	{"TestApp_CreateCannedResponse_SameNameDifferentOrgs", _xtest.TestApp_CreateCannedResponse_SameNameDifferentOrgs},

	{"TestApp_CreateCannedResponse_InvalidJSON", _xtest.TestApp_CreateCannedResponse_InvalidJSON},

	{"TestApp_CreateCannedResponse_WithAllOptionalFields", _xtest.TestApp_CreateCannedResponse_WithAllOptionalFields},

	{"TestApp_CreateCannedResponse_WithoutShortcutOrCategory", _xtest.TestApp_CreateCannedResponse_WithoutShortcutOrCategory},

	{"TestApp_ListCannedResponses_SearchByShortcut", _xtest.TestApp_ListCannedResponses_SearchByShortcut},

	{"TestApp_ListCannedResponses_OrderedByUsageCount", _xtest.TestApp_ListCannedResponses_OrderedByUsageCount},

	{"TestApp_ListCannedResponses_SearchByContent", _xtest.TestApp_ListCannedResponses_SearchByContent},

	{"TestApp_ListCannedResponses_CombinedCategoryAndSearch", _xtest.TestApp_ListCannedResponses_CombinedCategoryAndSearch},

	{"TestApp_UpdateCannedResponse_DeactivateResponse", _xtest.TestApp_UpdateCannedResponse_DeactivateResponse},

	{"TestApp_UpdateCannedResponse_ClearShortcutAndCategory", _xtest.TestApp_UpdateCannedResponse_ClearShortcutAndCategory},

	{"TestApp_UpdateCannedResponse_PreservesUsageCount", _xtest.TestApp_UpdateCannedResponse_PreservesUsageCount},

	{"TestApp_DeleteCannedResponse_DoubleDelete", _xtest.TestApp_DeleteCannedResponse_DoubleDelete},

	{"TestApp_DeleteCannedResponse_VerifyNotListedAfterDelete", _xtest.TestApp_DeleteCannedResponse_VerifyNotListedAfterDelete},

	{"TestApp_IncrementCannedResponseUsage_CrossOrgIsolation", _xtest.TestApp_IncrementCannedResponseUsage_CrossOrgIsolation},

	{"TestApp_IncrementCannedResponseUsage_ReflectedInGet", _xtest.TestApp_IncrementCannedResponseUsage_ReflectedInGet},

	{"TestApp_CannedResponse_FullLifecycle", _xtest.TestApp_CannedResponse_FullLifecycle},

	{"TestApp_IncrementCannedResponseUsage", _xtest.TestApp_IncrementCannedResponseUsage},

	{"TestApp_GetCloseRatingSettings_Defaults", _xtest.TestApp_GetCloseRatingSettings_Defaults},

	{"TestApp_GetCloseRatingSettings_AccountOverrides", _xtest.TestApp_GetCloseRatingSettings_AccountOverrides},

	{"TestApp_GetCloseRatingSettings_Unauthorized", _xtest.TestApp_GetCloseRatingSettings_Unauthorized},

	{"TestApp_GetCloseRatingSettings_NotFound", _xtest.TestApp_GetCloseRatingSettings_NotFound},

	{"TestApp_UpdateCloseRatingSettings_Success", _xtest.TestApp_UpdateCloseRatingSettings_Success},

	{"TestApp_UpdateCloseRatingSettings_Validation", _xtest.TestApp_UpdateCloseRatingSettings_Validation},

	{"TestApp_UpdateCloseRatingSettings_Unauthorized", _xtest.TestApp_UpdateCloseRatingSettings_Unauthorized},

	{"TestApp_GetCloseRatingStats", _xtest.TestApp_GetCloseRatingStats},

	{"TestApp_GetCloseRatingStats_Empty", _xtest.TestApp_GetCloseRatingStats_Empty},

	{"TestApp_ReleaseChat_Assignee_Success", _xtest.TestApp_ReleaseChat_Assignee_Success},

	{"TestApp_ReleaseChat_NonOwnerNonAdmin_Forbidden", _xtest.TestApp_ReleaseChat_NonOwnerNonAdmin_Forbidden},

	{"TestApp_ReleaseChat_ClosedChat_ByAgent_Forbidden", _xtest.TestApp_ReleaseChat_ClosedChat_ByAgent_Forbidden},

	{"TestApp_ReleaseChat_AlreadyPending_Idempotent", _xtest.TestApp_ReleaseChat_AlreadyPending_Idempotent},

	{"TestApp_ReleaseChat_NotFound", _xtest.TestApp_ReleaseChat_NotFound},

	{"TestApp_BulkReleaseChats_OwnerReleasesOwn", _xtest.TestApp_BulkReleaseChats_OwnerReleasesOwn},

	{"TestApp_BulkReleaseChats_EmptyList_BadRequest", _xtest.TestApp_BulkReleaseChats_EmptyList_BadRequest},

	{"TestApp_GetChatbotSettings", _xtest.TestApp_GetChatbotSettings},

	{"TestApp_UpdateChatbotSettings", _xtest.TestApp_UpdateChatbotSettings},

	{"TestApp_ListKeywordRules", _xtest.TestApp_ListKeywordRules},

	{"TestApp_CreateKeywordRule", _xtest.TestApp_CreateKeywordRule},

	{"TestApp_GetKeywordRule", _xtest.TestApp_GetKeywordRule},

	{"TestApp_UpdateKeywordRule", _xtest.TestApp_UpdateKeywordRule},

	{"TestApp_DeleteKeywordRule", _xtest.TestApp_DeleteKeywordRule},

	{"TestApp_ListChatbotFlows", _xtest.TestApp_ListChatbotFlows},

	{"TestApp_CreateChatbotFlow", _xtest.TestApp_CreateChatbotFlow},

	{"TestApp_GetChatbotFlow", _xtest.TestApp_GetChatbotFlow},

	{"TestApp_UpdateChatbotFlow", _xtest.TestApp_UpdateChatbotFlow},

	{"TestApp_DeleteChatbotFlow", _xtest.TestApp_DeleteChatbotFlow},

	{"TestApp_ListAIContexts", _xtest.TestApp_ListAIContexts},

	{"TestApp_CreateAIContext", _xtest.TestApp_CreateAIContext},

	{"TestApp_GetAIContext", _xtest.TestApp_GetAIContext},

	{"TestApp_DeleteAIContext", _xtest.TestApp_DeleteAIContext},

	{"TestApp_GetChatbotSettings_ExistingSettings", _xtest.TestApp_GetChatbotSettings_ExistingSettings},

	{"TestApp_UpdateChatbotSettings_PartialUpdate", _xtest.TestApp_UpdateChatbotSettings_PartialUpdate},

	{"TestApp_CreateKeywordRule_MatchTypes", _xtest.TestApp_CreateKeywordRule_MatchTypes},

	{"TestApp_UpdateKeywordRule_Additional", _xtest.TestApp_UpdateKeywordRule_Additional},

	{"TestApp_ListKeywordRules_OrgIsolation", _xtest.TestApp_ListKeywordRules_OrgIsolation},

	{"TestApp_CreateChatbotFlow_Additional", _xtest.TestApp_CreateChatbotFlow_Additional},

	{"TestApp_UpdateChatbotFlow_Additional", _xtest.TestApp_UpdateChatbotFlow_Additional},

	{"TestApp_ListChatbotFlows_OrgIsolation", _xtest.TestApp_ListChatbotFlows_OrgIsolation},

	{"TestApp_CreateAIContext_Additional", _xtest.TestApp_CreateAIContext_Additional},

	{"TestApp_UpdateAIContext", _xtest.TestApp_UpdateAIContext},

	{"TestApp_ListAIContexts_OrgIsolation", _xtest.TestApp_ListAIContexts_OrgIsolation},

	{"TestApp_DeleteKeywordRule_CrossOrg", _xtest.TestApp_DeleteKeywordRule_CrossOrg},

	{"TestApp_DeleteChatbotFlow_CrossOrg", _xtest.TestApp_DeleteChatbotFlow_CrossOrg},

	{"TestApp_DeleteAIContext_CrossOrg", _xtest.TestApp_DeleteAIContext_CrossOrg},

	{"TestApp_GetKeywordRule_CrossOrg", _xtest.TestApp_GetKeywordRule_CrossOrg},

	{"TestApp_GetChatbotFlow_CrossOrg", _xtest.TestApp_GetChatbotFlow_CrossOrg},

	{"TestApp_GetAIContext_CrossOrg", _xtest.TestApp_GetAIContext_CrossOrg},

	{"TestApp_GetKeywordRule_ResponseFields", _xtest.TestApp_GetKeywordRule_ResponseFields},

	{"TestApp_MarkContactRead_PendingUnclaimed_Forbidden", _xtest.TestApp_MarkContactRead_PendingUnclaimed_Forbidden},

	{"TestApp_MarkContactRead_Assignee_Success", _xtest.TestApp_MarkContactRead_Assignee_Success},

	{"TestApp_ListContacts", _xtest.TestApp_ListContacts},

	{"TestApp_GetContact", _xtest.TestApp_GetContact},

	{"TestApp_GetContactSessionData", _xtest.TestApp_GetContactSessionData},

	{"TestApp_AssignContact", _xtest.TestApp_AssignContact},

	{"TestApp_GetMessages", _xtest.TestApp_GetMessages},

	{"TestApp_SendMessage", _xtest.TestApp_SendMessage},

	{"TestApp_SendReaction", _xtest.TestApp_SendReaction},

	{"TestApp_ListContacts_SearchByProfileName", _xtest.TestApp_ListContacts_SearchByProfileName},

	{"TestApp_ListContacts_Page2", _xtest.TestApp_ListContacts_Page2},

	{"TestApp_GetMessages_AssignedViaActiveTransfer", _xtest.TestApp_GetMessages_AssignedViaActiveTransfer},

	{"TestApp_GetContact_WithAssignedUser", _xtest.TestApp_GetContact_WithAssignedUser},

	{"TestApp_GetContact_MultipleUnreadMessages", _xtest.TestApp_GetContact_MultipleUnreadMessages},

	{"TestApp_GetContactSessionData_CompletedSession", _xtest.TestApp_GetContactSessionData_CompletedSession},

	{"TestApp_GetContactSessionData_MostRecentSessionReturned", _xtest.TestApp_GetContactSessionData_MostRecentSessionReturned},

	{"TestApp_AssignContact_ReassignToAnotherUser", _xtest.TestApp_AssignContact_ReassignToAnotherUser},

	{"TestApp_AssignContact_AssignUserFromDifferentOrg", _xtest.TestApp_AssignContact_AssignUserFromDifferentOrg},

	{"TestApp_ListConversationNotes_Success", _xtest.TestApp_ListConversationNotes_Success},

	{"TestApp_ListConversationNotes_CrossOrgIsolation", _xtest.TestApp_ListConversationNotes_CrossOrgIsolation},

	{"TestApp_ListConversationNotes_PermissionDenied", _xtest.TestApp_ListConversationNotes_PermissionDenied},

	{"TestApp_CreateConversationNote_Success", _xtest.TestApp_CreateConversationNote_Success},

	{"TestApp_CreateConversationNote_EmptyContentRejected", _xtest.TestApp_CreateConversationNote_EmptyContentRejected},

	{"TestApp_CreateConversationNote_PermissionDenied", _xtest.TestApp_CreateConversationNote_PermissionDenied},

	{"TestApp_UpdateConversationNote_OnlyCreatorCanEdit", _xtest.TestApp_UpdateConversationNote_OnlyCreatorCanEdit},

	{"TestApp_UpdateConversationNote_NotFound", _xtest.TestApp_UpdateConversationNote_NotFound},

	{"TestApp_UpdateConversationNote_EmptyContentRejected", _xtest.TestApp_UpdateConversationNote_EmptyContentRejected},

	{"TestApp_DeleteConversationNote_OnlyCreatorCanDelete", _xtest.TestApp_DeleteConversationNote_OnlyCreatorCanDelete},

	{"TestApp_DeleteConversationNote_CrossOrgIsolation", _xtest.TestApp_DeleteConversationNote_CrossOrgIsolation},

	{"TestApp_ListCustomActions", _xtest.TestApp_ListCustomActions},

	{"TestApp_GetCustomAction", _xtest.TestApp_GetCustomAction},

	{"TestApp_CreateCustomAction", _xtest.TestApp_CreateCustomAction},

	{"TestApp_UpdateCustomAction", _xtest.TestApp_UpdateCustomAction},

	{"TestApp_DeleteCustomAction", _xtest.TestApp_DeleteCustomAction},

	{"TestApp_ListCustomActions_CrossOrgIsolation", _xtest.TestApp_ListCustomActions_CrossOrgIsolation},

	{"TestApp_GetCustomAction_CrossOrgIsolation", _xtest.TestApp_GetCustomAction_CrossOrgIsolation},

	{"TestApp_GetCustomAction_InvalidID", _xtest.TestApp_GetCustomAction_InvalidID},

	{"TestApp_UpdateCustomAction_InvalidActionType", _xtest.TestApp_UpdateCustomAction_InvalidActionType},

	{"TestApp_UpdateCustomAction_InvalidConfig", _xtest.TestApp_UpdateCustomAction_InvalidConfig},

	{"TestApp_ExecuteCustomAction", _xtest.TestApp_ExecuteCustomAction},

	{"TestApp_CustomActionRedirect", _xtest.TestApp_CustomActionRedirect},

	{"TestApp_CreateCustomAction_MissingConfig", _xtest.TestApp_CreateCustomAction_MissingConfig},

	{"TestApp_CreateCustomAction_DuplicateName", _xtest.TestApp_CreateCustomAction_DuplicateName},

	{"TestApp_UpdateCustomAction_ChangeActionType", _xtest.TestApp_UpdateCustomAction_ChangeActionType},

	{"TestApp_ListCustomActions_Unauthorized", _xtest.TestApp_ListCustomActions_Unauthorized},

	{"TestApp_GetCustomAction_Unauthorized", _xtest.TestApp_GetCustomAction_Unauthorized},

	{"TestApp_DeleteCustomAction_Unauthorized", _xtest.TestApp_DeleteCustomAction_Unauthorized},

	{"TestApp_UpdateCustomAction_Unauthorized", _xtest.TestApp_UpdateCustomAction_Unauthorized},

	{"TestApp_WaitForBackgroundTasks", _xtest.TestApp_WaitForBackgroundTasks},

	{"TestApp_DispatchWebhook_CompletesSuccessfully", _xtest.TestApp_DispatchWebhook_CompletesSuccessfully},

	{"TestApp_DispatchWebhook_ConcurrencyLimit", _xtest.TestApp_DispatchWebhook_ConcurrencyLimit},

	{"TestApp_DispatchWebhook_NoWebhooks", _xtest.TestApp_DispatchWebhook_NoWebhooks},

	{"TestApp_DispatchWebhook_InactiveWebhook", _xtest.TestApp_DispatchWebhook_InactiveWebhook},

	{"TestApp_DispatchWebhook_EventFiltering", _xtest.TestApp_DispatchWebhook_EventFiltering},

	{"TestApp_DispatchWebhook_RetryOnFailure", _xtest.TestApp_DispatchWebhook_RetryOnFailure},

	{"TestApp_DispatchWebhook_HTTPTimeout", _xtest.TestApp_DispatchWebhook_HTTPTimeout},

	{"TestApp_DispatchWebhook_MultipleEvents", _xtest.TestApp_DispatchWebhook_MultipleEvents},

	{"TestSyncGowaInstanceDeviceContacts_ImportsChats", _xtest.TestSyncGowaInstanceDeviceContacts_ImportsChats},

	{"TestSyncGowaInstanceDeviceContacts_NeedsAccountProvisioning", _xtest.TestSyncGowaInstanceDeviceContacts_NeedsAccountProvisioning},

	{"TestSyncGowaInstanceDeviceContacts_Idempotent", _xtest.TestSyncGowaInstanceDeviceContacts_Idempotent},

	{"TestSyncGowaInstanceDeviceContacts_OverwritesStaleAccount", _xtest.TestSyncGowaInstanceDeviceContacts_OverwritesStaleAccount},

	{"TestSyncGowaInstanceDeviceContacts_AgentDenied", _xtest.TestSyncGowaInstanceDeviceContacts_AgentDenied},

	{"TestGowaDevice_AdminCanListInstances", _xtest.TestGowaDevice_AdminCanListInstances},

	{"TestGowaDevice_CrossOrgProvisioning_Refused", _xtest.TestGowaDevice_CrossOrgProvisioning_Refused},

	{"TestGowaCreateDevice_WebhookSecret_NotExposedToAgent", _xtest.TestGowaCreateDevice_WebhookSecret_NotExposedToAgent},

	{"TestPermissions_DevicesSeeded", _xtest.TestPermissions_DevicesSeeded},

	{"TestSystemRoles_DevicesMapping", _xtest.TestSystemRoles_DevicesMapping},

	{"TestGowaWebhookSecret_AutoGenerated_OnCreate", _xtest.TestGowaWebhookSecret_AutoGenerated_OnCreate},

	{"TestBackfillGowaWebhookSecrets", _xtest.TestBackfillGowaWebhookSecrets},

	{"TestGowaWebhook_MissingSignature_Rejected", _xtest.TestGowaWebhook_MissingSignature_Rejected},

	{"TestGowaWebhook_TamperedBody_Rejected", _xtest.TestGowaWebhook_TamperedBody_Rejected},

	{"TestGowaWebhook_EmptySecret_Rejected", _xtest.TestGowaWebhook_EmptySecret_Rejected},

	{"TestMediaZip_ExportPermission_Required", _xtest.TestMediaZip_ExportPermission_Required},

	{"TestGowaWebhook_ReactionWithoutTimestamp_Accepted", _xtest.TestGowaWebhook_ReactionWithoutTimestamp_Accepted},

	{"TestApp_GowaPairCode_ReturnsCodeFromGOWA", _xtest.TestApp_GowaPairCode_ReturnsCodeFromGOWA},

	{"TestApp_GowaPairCode_EmptyPhoneRejected", _xtest.TestApp_GowaPairCode_EmptyPhoneRejected},

	{"TestGowaInstances_AgentDenied_CRUD", _xtest.TestGowaInstances_AgentDenied_CRUD},

	{"TestGowaInstances_CredentialsNotExposed", _xtest.TestGowaInstances_CredentialsNotExposed},

	{"TestGowaInstances_CrossOrgDenied", _xtest.TestGowaInstances_CrossOrgDenied},

	{"TestGowaInstances_Create_EncryptsAndStripsCreds", _xtest.TestGowaInstances_Create_EncryptsAndStripsCreds},

	{"TestGowaInstanceDevices_AgentDenied", _xtest.TestGowaInstanceDevices_AgentDenied},

	{"TestGowaInstanceDevices_CrossOrgDenied", _xtest.TestGowaInstanceDevices_CrossOrgDenied},

	{"TestSyncGowaInstanceMessages_MediaUrlNotWrittenForUndownloadedBytes", _xtest.TestSyncGowaInstanceMessages_MediaUrlNotWrittenForUndownloadedBytes},

	{"TestE2E_GOWAAccountResolvesGOWAProvider", _xtest.TestE2E_GOWAAccountResolvesGOWAProvider},

	{"TestE2E_Registry_GOWADownReturnsErrorNotMetaFallback", _xtest.TestE2E_Registry_GOWADownReturnsErrorNotMetaFallback},

	{"TestE2E_GOWASendText_VerifiesHTTPFormat", _xtest.TestE2E_GOWASendText_VerifiesHTTPFormat},

	{"TestE2E_GOWASendImage_MultipartNotTwoStep", _xtest.TestE2E_GOWASendImage_MultipartNotTwoStep},

	{"TestE2E_GOWAWebhook_TextMessageNormalization", _xtest.TestE2E_GOWAWebhook_TextMessageNormalization},

	{"TestE2E_GOWAWebhook_ImageMessageNormalization", _xtest.TestE2E_GOWAWebhook_ImageMessageNormalization},

	{"TestE2E_GOWAWebhook_AckBatchIDs", _xtest.TestE2E_GOWAWebhook_AckBatchIDs},

	{"TestE2E_GOWAWebhook_GroupMessage", _xtest.TestE2E_GOWAWebhook_GroupMessage},

	{"TestE2E_GOWAWebhook_ConnectionEvent", _xtest.TestE2E_GOWAWebhook_ConnectionEvent},

	{"TestApp_GetExportConfig_Contacts", _xtest.TestApp_GetExportConfig_Contacts},

	{"TestApp_GetExportConfig_InvalidTable", _xtest.TestApp_GetExportConfig_InvalidTable},

	{"TestApp_GetExportConfig_PermissionDenied", _xtest.TestApp_GetExportConfig_PermissionDenied},

	{"TestApp_GetImportConfig_Contacts", _xtest.TestApp_GetImportConfig_Contacts},

	{"TestApp_GetImportConfig_InvalidTable", _xtest.TestApp_GetImportConfig_InvalidTable},

	{"TestApp_ExportData_Contacts_OnlyOwnOrg", _xtest.TestApp_ExportData_Contacts_OnlyOwnOrg},

	{"TestApp_ExportData_RejectsDisallowedColumn", _xtest.TestApp_ExportData_RejectsDisallowedColumn},

	{"TestApp_ExportData_PermissionDenied", _xtest.TestApp_ExportData_PermissionDenied},

	{"TestApp_ExportData_InvalidTable", _xtest.TestApp_ExportData_InvalidTable},

	{"TestApp_ExportData_InvalidJSONBody", _xtest.TestApp_ExportData_InvalidJSONBody},

	{"TestApp_ExportData_DefaultColumnsWhenEmpty", _xtest.TestApp_ExportData_DefaultColumnsWhenEmpty},

	{"TestApp_ExportData_CSVInjectionEscaped", _xtest.TestApp_ExportData_CSVInjectionEscaped},

	{"TestApp_ServeMedia_Success_WithContactsRead", _xtest.TestApp_ServeMedia_Success_WithContactsRead},

	{"TestApp_ServeMedia_RejectsDirectoryTraversal", _xtest.TestApp_ServeMedia_RejectsDirectoryTraversal},

	{"TestApp_ServeMedia_RejectsSymlink", _xtest.TestApp_ServeMedia_RejectsSymlink},

	{"TestApp_ServeMedia_FileMissingOnDisk", _xtest.TestApp_ServeMedia_FileMissingOnDisk},

	{"TestApp_ServeMedia_CrossOrgIsolation", _xtest.TestApp_ServeMedia_CrossOrgIsolation},

	{"TestApp_ServeMedia_AgentCanReadAssignedContactMedia", _xtest.TestApp_ServeMedia_AgentCanReadAssignedContactMedia},

	{"TestApp_ServeMedia_AgentWithoutAssignmentDenied", _xtest.TestApp_ServeMedia_AgentWithoutAssignmentDenied},

	{"TestApp_ServeMedia_AgentViaDirectTransfer", _xtest.TestApp_ServeMedia_AgentViaDirectTransfer},

	{"TestApp_ServeMedia_AgentViaTeamTransfer", _xtest.TestApp_ServeMedia_AgentViaTeamTransfer},

	{"TestApp_ServeMedia_NoMediaInMessage", _xtest.TestApp_ServeMedia_NoMediaInMessage},

	{"TestApp_ServeMedia_InvalidMessageID", _xtest.TestApp_ServeMedia_InvalidMessageID},

	{"TestApp_ServeMedia_Unauthorized", _xtest.TestApp_ServeMedia_Unauthorized},

	{"TestServeMediaZip_NoIDs", _xtest.TestServeMediaZip_NoIDs},

	{"TestServeMediaZip_OrgIsolation", _xtest.TestServeMediaZip_OrgIsolation},

	{"TestServeMediaZip_FilenameCollision", _xtest.TestServeMediaZip_FilenameCollision},

	{"TestServeMediaZip_PathTraversalSkipped", _xtest.TestServeMediaZip_PathTraversalSkipped},

	{"TestServeMediaZip_Manifest", _xtest.TestServeMediaZip_Manifest},

	{"TestApp_SendOutgoingMessage_TextMessage_Success", _xtest.TestApp_SendOutgoingMessage_TextMessage_Success},

	{"TestApp_SendOutgoingMessage_TextMessage_APIError", _xtest.TestApp_SendOutgoingMessage_TextMessage_APIError},

	{"TestApp_SendOutgoingMessage_ImageMessage_WithMediaID", _xtest.TestApp_SendOutgoingMessage_ImageMessage_WithMediaID},

	{"TestApp_SendOutgoingMessage_ImageMessage_WithMediaData", _xtest.TestApp_SendOutgoingMessage_ImageMessage_WithMediaData},

	{"TestApp_SendOutgoingMessage_DocumentMessage", _xtest.TestApp_SendOutgoingMessage_DocumentMessage},

	{"TestApp_SendOutgoingMessage_VideoMessage", _xtest.TestApp_SendOutgoingMessage_VideoMessage},

	{"TestApp_SendOutgoingMessage_AudioMessage", _xtest.TestApp_SendOutgoingMessage_AudioMessage},

	{"TestApp_SendOutgoingMessage_InteractiveButtons", _xtest.TestApp_SendOutgoingMessage_InteractiveButtons},

	{"TestApp_SendOutgoingMessage_InteractiveCTAURL", _xtest.TestApp_SendOutgoingMessage_InteractiveCTAURL},

	{"TestApp_SendOutgoingMessage_TemplateMessage", _xtest.TestApp_SendOutgoingMessage_TemplateMessage},

	{"TestApp_SendOutgoingMessage_TemplateMessage_MissingTemplate", _xtest.TestApp_SendOutgoingMessage_TemplateMessage_MissingTemplate},

	{"TestApp_SendOutgoingMessage_AsyncOption", _xtest.TestApp_SendOutgoingMessage_AsyncOption},

	{"TestApp_SendOutgoingMessage_SyncOption", _xtest.TestApp_SendOutgoingMessage_SyncOption},

	{"TestApp_SendOutgoingMessage_WithSentByUser", _xtest.TestApp_SendOutgoingMessage_WithSentByUser},

	{"TestApp_SendOutgoingMessage_UnsupportedType", _xtest.TestApp_SendOutgoingMessage_UnsupportedType},

	{"TestDefaultSendOptions", _xtest.TestDefaultSendOptions},

	{"TestChatbotSendOptions", _xtest.TestChatbotSendOptions},

	{"TestAPISendOptions", _xtest.TestAPISendOptions},

	{"TestSLASendOptions", _xtest.TestSLASendOptions},

	{"TestApp_SendOutgoingMessage_ContactLastMessageUpdated", _xtest.TestApp_SendOutgoingMessage_ContactLastMessageUpdated},

	{"TestApp_SendOutgoingMessage_MediaPreview", _xtest.TestApp_SendOutgoingMessage_MediaPreview},

	{"TestApp_SendOutgoingMessage_DocumentPreview", _xtest.TestApp_SendOutgoingMessage_DocumentPreview},

	{"TestExtractParamNamesFromContent_Positional", _xtest.TestExtractParamNamesFromContent_Positional},

	{"TestExtractParamNamesFromContent_Named", _xtest.TestExtractParamNamesFromContent_Named},

	{"TestExtractParamNamesFromContent_Mixed", _xtest.TestExtractParamNamesFromContent_Mixed},

	{"TestExtractParamNamesFromContent_NoParams", _xtest.TestExtractParamNamesFromContent_NoParams},

	{"TestExtractParamNamesFromContent_DuplicateParams", _xtest.TestExtractParamNamesFromContent_DuplicateParams},

	{"TestResolveParams_NamedMatch", _xtest.TestResolveParams_NamedMatch},

	{"TestResolveParams_PositionalMatch", _xtest.TestResolveParams_PositionalMatch},

	{"TestResolveParams_FallbackToPositional", _xtest.TestResolveParams_FallbackToPositional},

	{"TestResolveParams_MissingParams", _xtest.TestResolveParams_MissingParams},

	{"TestResolveParams_EmptyInputs", _xtest.TestResolveParams_EmptyInputs},

	{"TestResolveParams_WrongParamNames", _xtest.TestResolveParams_WrongParamNames},

	{"TestApp_CreateOrganization_Success", _xtest.TestApp_CreateOrganization_Success},

	{"TestApp_CreateOrganization_EmptyName", _xtest.TestApp_CreateOrganization_EmptyName},

	{"TestApp_CreateOrganization_Unauthorized", _xtest.TestApp_CreateOrganization_Unauthorized},

	{"TestApp_AddOrganizationMember_Success", _xtest.TestApp_AddOrganizationMember_Success},

	{"TestApp_AddOrganizationMember_WithRole", _xtest.TestApp_AddOrganizationMember_WithRole},

	{"TestApp_AddOrganizationMember_AlreadyMember", _xtest.TestApp_AddOrganizationMember_AlreadyMember},

	{"TestApp_AddOrganizationMember_MissingUserID", _xtest.TestApp_AddOrganizationMember_MissingUserID},

	{"TestApp_AddOrganizationMember_UserNotFound", _xtest.TestApp_AddOrganizationMember_UserNotFound},

	{"TestApp_AddOrganizationMember_Unauthorized", _xtest.TestApp_AddOrganizationMember_Unauthorized},

	{"TestApp_ListMyOrganizations_Success", _xtest.TestApp_ListMyOrganizations_Success},

	{"TestApp_ListMyOrganizations_SingleOrg", _xtest.TestApp_ListMyOrganizations_SingleOrg},

	{"TestApp_ListMyOrganizations_Unauthorized", _xtest.TestApp_ListMyOrganizations_Unauthorized},

	{"TestApp_SwitchOrg_Success", _xtest.TestApp_SwitchOrg_Success},

	{"TestApp_SwitchOrg_SuperAdmin", _xtest.TestApp_SwitchOrg_SuperAdmin},

	{"TestApp_SwitchOrg_NotMember", _xtest.TestApp_SwitchOrg_NotMember},

	{"TestApp_SwitchOrg_OrgNotFound", _xtest.TestApp_SwitchOrg_OrgNotFound},

	{"TestApp_SwitchOrg_MissingOrgID", _xtest.TestApp_SwitchOrg_MissingOrgID},

	{"TestApp_SwitchOrg_Unauthorized", _xtest.TestApp_SwitchOrg_Unauthorized},

	{"TestApp_GetOrganizationSettings_Success", _xtest.TestApp_GetOrganizationSettings_Success},

	{"TestApp_GetOrganizationSettings_Defaults", _xtest.TestApp_GetOrganizationSettings_Defaults},

	{"TestApp_GetOrganizationSettings_Unauthorized", _xtest.TestApp_GetOrganizationSettings_Unauthorized},

	{"TestApp_UpdateOrganizationSettings_Success", _xtest.TestApp_UpdateOrganizationSettings_Success},

	{"TestApp_UpdateOrganizationSettings_PartialUpdate", _xtest.TestApp_UpdateOrganizationSettings_PartialUpdate},

	{"TestApp_UpdateOrganizationSettings_Unauthorized", _xtest.TestApp_UpdateOrganizationSettings_Unauthorized},

	{"TestApp_UpdateOrganizationSettings_EmptyNameIgnored", _xtest.TestApp_UpdateOrganizationSettings_EmptyNameIgnored},

	{"TestApp_UpdateOrganizationSettings_InvalidJSON", _xtest.TestApp_UpdateOrganizationSettings_InvalidJSON},

	{"TestApp_ListRoles_Success", _xtest.TestApp_ListRoles_Success},

	{"TestApp_GetRole_Success", _xtest.TestApp_GetRole_Success},

	{"TestApp_GetRole_NotFound", _xtest.TestApp_GetRole_NotFound},

	{"TestApp_CreateRole_Success", _xtest.TestApp_CreateRole_Success},

	{"TestApp_CreateRole_DuplicateName", _xtest.TestApp_CreateRole_DuplicateName},

	{"TestApp_CreateRole_MissingName", _xtest.TestApp_CreateRole_MissingName},

	{"TestApp_CreateRole_WithDefaultFlag", _xtest.TestApp_CreateRole_WithDefaultFlag},

	{"TestApp_UpdateRole_Success", _xtest.TestApp_UpdateRole_Success},

	{"TestApp_UpdateRole_SystemRoleOnlyDescription", _xtest.TestApp_UpdateRole_SystemRoleOnlyDescription},

	{"TestApp_UpdateRole_NotFound", _xtest.TestApp_UpdateRole_NotFound},

	{"TestApp_DeleteRole_Success", _xtest.TestApp_DeleteRole_Success},

	{"TestApp_DeleteRole_SystemRole", _xtest.TestApp_DeleteRole_SystemRole},

	{"TestApp_DeleteRole_WithAssignedUsers", _xtest.TestApp_DeleteRole_WithAssignedUsers},

	{"TestApp_ListPermissions_Success", _xtest.TestApp_ListPermissions_Success},

	{"TestApp_SendTemplateMessage", _xtest.TestApp_SendTemplateMessage},

	{"TestSetSLADeadlines_AllFieldsSet", _xtest.TestSetSLADeadlines_AllFieldsSet},

	{"TestSetSLADeadlines_DisabledSLA", _xtest.TestSetSLADeadlines_DisabledSLA},

	{"TestSetSLADeadlines_PartialConfig", _xtest.TestSetSLADeadlines_PartialConfig},

	{"TestUpdateSLAOnPickup_WithinDeadline", _xtest.TestUpdateSLAOnPickup_WithinDeadline},

	{"TestUpdateSLAOnPickup_AfterDeadline", _xtest.TestUpdateSLAOnPickup_AfterDeadline},

	{"TestUpdateSLAOnPickup_NoDeadline", _xtest.TestUpdateSLAOnPickup_NoDeadline},

	{"TestUpdateSLAOnFirstResponse_SetsTimestamp", _xtest.TestUpdateSLAOnFirstResponse_SetsTimestamp},

	{"TestUpdateSLAOnFirstResponse_SkipsIfAlreadyResponded", _xtest.TestUpdateSLAOnFirstResponse_SkipsIfAlreadyResponded},

	{"TestUpdateContactChatbotMessage_SetsTimestampAndResetsReminder", _xtest.TestUpdateContactChatbotMessage_SetsTimestampAndResetsReminder},

	{"TestClearContactChatbotTracking_ClearsFields", _xtest.TestClearContactChatbotTracking_ClearsFields},

	{"TestClearContactChatbotTracking_NopWhenAlreadyClear", _xtest.TestClearContactChatbotTracking_NopWhenAlreadyClear},

	{"TestApp_GetPublicSSOProviders_DedupsByType", _xtest.TestApp_GetPublicSSOProviders_DedupsByType},

	{"TestApp_GetSSOSettings_HidesSecretButReportsHasSecret", _xtest.TestApp_GetSSOSettings_HidesSecretButReportsHasSecret},

	{"TestApp_UpdateSSOProvider_CreateCustomRequiresURLs", _xtest.TestApp_UpdateSSOProvider_CreateCustomRequiresURLs},

	{"TestApp_UpdateSSOProvider_InvalidProviderRejected", _xtest.TestApp_UpdateSSOProvider_InvalidProviderRejected},

	{"TestApp_UpdateSSOProvider_EncryptsClientSecret", _xtest.TestApp_UpdateSSOProvider_EncryptsClientSecret},

	{"TestApp_UpdateSSOProvider_OmittingSecretLeavesUnchanged", _xtest.TestApp_UpdateSSOProvider_OmittingSecretLeavesUnchanged},

	{"TestApp_DeleteSSOProvider_Success", _xtest.TestApp_DeleteSSOProvider_Success},

	{"TestApp_DeleteSSOProvider_NotFound", _xtest.TestApp_DeleteSSOProvider_NotFound},

	{"TestApp_DeleteSSOProvider_CrossOrgIsolation", _xtest.TestApp_DeleteSSOProvider_CrossOrgIsolation},

	{"TestApp_InitSSO_InvalidProviderRejected", _xtest.TestApp_InitSSO_InvalidProviderRejected},

	{"TestApp_InitSSO_NoConfigReturns404", _xtest.TestApp_InitSSO_NoConfigReturns404},

	{"TestApp_InitSSO_StoresStateInRedisAndRedirects", _xtest.TestApp_InitSSO_StoresStateInRedisAndRedirects},

	{"TestApp_CallbackSSO_MissingCodeOrStateRedirectsWithError", _xtest.TestApp_CallbackSSO_MissingCodeOrStateRedirectsWithError},

	{"TestApp_CallbackSSO_OAuthErrorParamRedirects", _xtest.TestApp_CallbackSSO_OAuthErrorParamRedirects},

	{"TestApp_CallbackSSO_UnknownStateNonceFails", _xtest.TestApp_CallbackSSO_UnknownStateNonceFails},

	{"TestApp_CallbackSSO_StateProviderMismatchRejected", _xtest.TestApp_CallbackSSO_StateProviderMismatchRejected},

	{"TestApp_CallbackSSO_StateIsSingleUse", _xtest.TestApp_CallbackSSO_StateIsSingleUse},

	{"TestApp_CallbackSSO_CustomProvider_ExistingUser_LoginSuccess", _xtest.TestApp_CallbackSSO_CustomProvider_ExistingUser_LoginSuccess},

	{"TestApp_CallbackSSO_AutoCreateDisabledRejectsNewUser", _xtest.TestApp_CallbackSSO_AutoCreateDisabledRejectsNewUser},

	{"TestApp_CallbackSSO_AutoCreateEnabledCreatesUserWithDefaultRole", _xtest.TestApp_CallbackSSO_AutoCreateEnabledCreatesUserWithDefaultRole},

	{"TestApp_CallbackSSO_DomainRestrictionRejectsOutsideEmail", _xtest.TestApp_CallbackSSO_DomainRestrictionRejectsOutsideEmail},

	{"TestApp_CallbackSSO_DisabledExistingUserRejected", _xtest.TestApp_CallbackSSO_DisabledExistingUserRejected},

	{"TestApp_ListTags", _xtest.TestApp_ListTags},

	{"TestApp_CreateTag", _xtest.TestApp_CreateTag},

	{"TestApp_UpdateTag", _xtest.TestApp_UpdateTag},

	{"TestApp_DeleteTag", _xtest.TestApp_DeleteTag},

	{"TestApp_Tag_FullLifecycle", _xtest.TestApp_Tag_FullLifecycle},

	{"TestApp_CreateTag_AllValidColors", _xtest.TestApp_CreateTag_AllValidColors},

	{"TestApp_ListTeams_Success", _xtest.TestApp_ListTeams_Success},

	{"TestApp_ListTeams_Empty", _xtest.TestApp_ListTeams_Empty},

	{"TestApp_GetTeam_Success", _xtest.TestApp_GetTeam_Success},

	{"TestApp_GetTeam_NotFound", _xtest.TestApp_GetTeam_NotFound},

	{"TestApp_CreateTeam_Success", _xtest.TestApp_CreateTeam_Success},

	{"TestApp_CreateTeam_DefaultStrategy", _xtest.TestApp_CreateTeam_DefaultStrategy},

	{"TestApp_CreateTeam_MissingName", _xtest.TestApp_CreateTeam_MissingName},

	{"TestApp_UpdateTeam_Success", _xtest.TestApp_UpdateTeam_Success},

	{"TestApp_UpdateTeam_NotFound", _xtest.TestApp_UpdateTeam_NotFound},

	{"TestApp_DeleteTeam_Success", _xtest.TestApp_DeleteTeam_Success},

	{"TestApp_DeleteTeam_NotFound", _xtest.TestApp_DeleteTeam_NotFound},

	{"TestApp_ListTeamMembers_Success", _xtest.TestApp_ListTeamMembers_Success},

	{"TestApp_ListTeamMembers_TeamNotFound", _xtest.TestApp_ListTeamMembers_TeamNotFound},

	{"TestApp_AddTeamMember_Success", _xtest.TestApp_AddTeamMember_Success},

	{"TestApp_AddTeamMember_DuplicateMember", _xtest.TestApp_AddTeamMember_DuplicateMember},

	{"TestApp_RemoveTeamMember_Success", _xtest.TestApp_RemoveTeamMember_Success},

	{"TestApp_RemoveTeamMember_NotFound", _xtest.TestApp_RemoveTeamMember_NotFound},

	{"TestExtParamNames_PositionalParams", _xtest.TestExtParamNames_PositionalParams},

	{"TestExtParamNames_NamedParams", _xtest.TestExtParamNames_NamedParams},

	{"TestExtParamNames_MixedParams", _xtest.TestExtParamNames_MixedParams},

	{"TestExtParamNames_NoParams", _xtest.TestExtParamNames_NoParams},

	{"TestExtParamNames_DuplicateParams", _xtest.TestExtParamNames_DuplicateParams},

	{"TestExtParamNames_UnderscoreParams", _xtest.TestExtParamNames_UnderscoreParams},

	{"TestApp_ListTemplates_Success", _xtest.TestApp_ListTemplates_Success},

	{"TestApp_ListTemplates_EmptyList", _xtest.TestApp_ListTemplates_EmptyList},

	{"TestApp_ListTemplates_FilterByAccount", _xtest.TestApp_ListTemplates_FilterByAccount},

	{"TestApp_ListTemplates_FilterByCategory", _xtest.TestApp_ListTemplates_FilterByCategory},

	{"TestApp_ListTemplates_CrossOrgIsolation", _xtest.TestApp_ListTemplates_CrossOrgIsolation},

	{"TestApp_GetTemplate_Success", _xtest.TestApp_GetTemplate_Success},

	{"TestApp_GetTemplate_NotFound", _xtest.TestApp_GetTemplate_NotFound},

	{"TestApp_GetTemplate_InvalidID", _xtest.TestApp_GetTemplate_InvalidID},

	{"TestApp_GetTemplate_CrossOrgIsolation", _xtest.TestApp_GetTemplate_CrossOrgIsolation},

	{"TestApp_ListUsers", _xtest.TestApp_ListUsers},

	{"TestApp_GetUser", _xtest.TestApp_GetUser},

	{"TestApp_CreateUser", _xtest.TestApp_CreateUser},

	{"TestApp_UpdateUser", _xtest.TestApp_UpdateUser},

	{"TestApp_DeleteUser", _xtest.TestApp_DeleteUser},

	{"TestApp_GetCurrentUser", _xtest.TestApp_GetCurrentUser},

	{"TestApp_UpdateAvailability", _xtest.TestApp_UpdateAvailability},

	{"TestApp_ChangePassword", _xtest.TestApp_ChangePassword},

	{"TestApp_UpdateCurrentUserSettings", _xtest.TestApp_UpdateCurrentUserSettings},

	{"TestApp_CrossOrgIsolation", _xtest.TestApp_CrossOrgIsolation},

	{"TestApp_DeleteUser_InvalidUUID", _xtest.TestApp_DeleteUser_InvalidUUID},

	{"TestApp_DeleteUser_LastAdmin", _xtest.TestApp_DeleteUser_LastAdmin},

	{"TestApp_UpdateUser_InvalidUUID", _xtest.TestApp_UpdateUser_InvalidUUID},

	{"TestApp_UpdateUser_ForbiddenWithoutPermission", _xtest.TestApp_UpdateUser_ForbiddenWithoutPermission},

	{"TestApp_UpdateUser_CannotDeactivateSelf", _xtest.TestApp_UpdateUser_CannotDeactivateSelf},

	{"TestApp_UpdateUser_DeactivateOtherUser", _xtest.TestApp_UpdateUser_DeactivateOtherUser},

	{"TestApp_UpdateUser_ChangeRole", _xtest.TestApp_UpdateUser_ChangeRole},

	{"TestApp_UpdateUser_RoleChangeWithoutPermission", _xtest.TestApp_UpdateUser_RoleChangeWithoutPermission},

	{"TestApp_CreateUser_InvalidRoleID", _xtest.TestApp_CreateUser_InvalidRoleID},

	{"TestApp_CreateUser_RoleFromDifferentOrg", _xtest.TestApp_CreateUser_RoleFromDifferentOrg},

	{"TestApp_GetCurrentUser_NotFound", _xtest.TestApp_GetCurrentUser_NotFound},

	{"TestApp_UpdateAvailability_NoChangeNoNewLog", _xtest.TestApp_UpdateAvailability_NoChangeNoNewLog},

	{"TestApp_ListUsers_CrossOrgExclusion", _xtest.TestApp_ListUsers_CrossOrgExclusion},

	{"TestApp_ChangePassword_OldPasswordStopsWorking", _xtest.TestApp_ChangePassword_OldPasswordStopsWorking},

	{"TestApp_GetUser_VerifyResponseFields", _xtest.TestApp_GetUser_VerifyResponseFields},

	{"TestApp_CreateUser_CreatedUserIsActive", _xtest.TestApp_CreateUser_CreatedUserIsActive},

	{"TestApp_ListWebhooks_Success", _xtest.TestApp_ListWebhooks_Success},

	{"TestApp_ListWebhooks_Empty", _xtest.TestApp_ListWebhooks_Empty},

	{"TestApp_ListWebhooks_OrgIsolation", _xtest.TestApp_ListWebhooks_OrgIsolation},

	{"TestApp_ListWebhooks_Unauthorized", _xtest.TestApp_ListWebhooks_Unauthorized},

	{"TestApp_GetWebhook_Success", _xtest.TestApp_GetWebhook_Success},

	{"TestApp_GetWebhook_NotFound", _xtest.TestApp_GetWebhook_NotFound},

	{"TestApp_GetWebhook_InvalidID", _xtest.TestApp_GetWebhook_InvalidID},

	{"TestApp_GetWebhook_CrossOrgIsolation", _xtest.TestApp_GetWebhook_CrossOrgIsolation},

	{"TestApp_CreateWebhook_Success", _xtest.TestApp_CreateWebhook_Success},

	{"TestApp_CreateWebhook_MissingName", _xtest.TestApp_CreateWebhook_MissingName},

	{"TestApp_CreateWebhook_MissingURL", _xtest.TestApp_CreateWebhook_MissingURL},

	{"TestApp_CreateWebhook_MissingEvents", _xtest.TestApp_CreateWebhook_MissingEvents},

	{"TestApp_CreateWebhook_EmptyEvents", _xtest.TestApp_CreateWebhook_EmptyEvents},

	{"TestApp_CreateWebhook_Unauthorized", _xtest.TestApp_CreateWebhook_Unauthorized},

	{"TestApp_UpdateWebhook_Success", _xtest.TestApp_UpdateWebhook_Success},

	{"TestApp_UpdateWebhook_PartialUpdate", _xtest.TestApp_UpdateWebhook_PartialUpdate},

	{"TestApp_UpdateWebhook_NotFound", _xtest.TestApp_UpdateWebhook_NotFound},

	{"TestApp_UpdateWebhook_InvalidID", _xtest.TestApp_UpdateWebhook_InvalidID},

	{"TestApp_DeleteWebhook_Success", _xtest.TestApp_DeleteWebhook_Success},

	{"TestApp_DeleteWebhook_NotFound", _xtest.TestApp_DeleteWebhook_NotFound},

	{"TestApp_DeleteWebhook_InvalidID", _xtest.TestApp_DeleteWebhook_InvalidID},

	{"TestApp_DeleteWebhook_CrossOrgIsolation", _xtest.TestApp_DeleteWebhook_CrossOrgIsolation},

	{"TestApp_TestWebhook_Success", _xtest.TestApp_TestWebhook_Success},

	{"TestApp_TestWebhook_ServerError", _xtest.TestApp_TestWebhook_ServerError},

	{"TestApp_TestWebhook_NotFound", _xtest.TestApp_TestWebhook_NotFound},

	{"TestApp_TestWebhook_Unauthorized", _xtest.TestApp_TestWebhook_Unauthorized},

	{"TestWebhookToResponse_HasSecretTrue", _xtest.TestWebhookToResponse_HasSecretTrue},

	{"TestWebhookToResponse_HasSecretFalse", _xtest.TestWebhookToResponse_HasSecretFalse},

	{"TestApp_ListWidgets_Success", _xtest.TestApp_ListWidgets_Success},

	{"TestApp_ListWidgets_NoPermission", _xtest.TestApp_ListWidgets_NoPermission},

	{"TestApp_ListWidgets_FiltersByOrganization", _xtest.TestApp_ListWidgets_FiltersByOrganization},

	{"TestApp_ListWidgets_Unauthorized", _xtest.TestApp_ListWidgets_Unauthorized},

	{"TestApp_GetWidget_Success", _xtest.TestApp_GetWidget_Success},

	{"TestApp_GetWidget_NoPermission", _xtest.TestApp_GetWidget_NoPermission},

	{"TestApp_GetWidget_NotFound", _xtest.TestApp_GetWidget_NotFound},

	{"TestApp_GetWidget_InvalidID", _xtest.TestApp_GetWidget_InvalidID},

	{"TestApp_CreateWidget_Success", _xtest.TestApp_CreateWidget_Success},

	{"TestApp_CreateWidget_NoPermission", _xtest.TestApp_CreateWidget_NoPermission},

	{"TestApp_CreateWidget_WithFilters", _xtest.TestApp_CreateWidget_WithFilters},

	{"TestApp_CreateWidget_InvalidDataSource", _xtest.TestApp_CreateWidget_InvalidDataSource},

	{"TestApp_CreateWidget_MissingName", _xtest.TestApp_CreateWidget_MissingName},

	{"TestApp_CreateWidget_Unauthorized", _xtest.TestApp_CreateWidget_Unauthorized},

	{"TestApp_UpdateWidget_Success", _xtest.TestApp_UpdateWidget_Success},

	{"TestApp_UpdateWidget_NoPermission", _xtest.TestApp_UpdateWidget_NoPermission},

	{"TestApp_UpdateWidget_OnlyOwnerCanEdit", _xtest.TestApp_UpdateWidget_OnlyOwnerCanEdit},

	{"TestApp_UpdateWidget_NotFound", _xtest.TestApp_UpdateWidget_NotFound},

	{"TestApp_DeleteWidget_Success", _xtest.TestApp_DeleteWidget_Success},

	{"TestApp_DeleteWidget_NoPermission", _xtest.TestApp_DeleteWidget_NoPermission},

	{"TestApp_DeleteWidget_OnlyOwnerCanDelete", _xtest.TestApp_DeleteWidget_OnlyOwnerCanDelete},

	{"TestApp_DeleteWidget_NotFound", _xtest.TestApp_DeleteWidget_NotFound},

	{"TestApp_Widget_CrossOrgIsolation", _xtest.TestApp_Widget_CrossOrgIsolation},

	{"TestApp_Widget_CrossOrg_CannotDelete", _xtest.TestApp_Widget_CrossOrg_CannotDelete},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/shridarpatil/whatomate"
	testdeps.ImportPath = "github.com/shridarpatil/whatomate/internal/handlers"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

