import {
  LayoutDashboard,
  MessageSquare,
  Bot,
  FileText,
  Megaphone,
  Settings,
  Users,
  Contact,
  Workflow,
  Sparkles,
  Key,
  UserX,
  MessageSquareText,
  Webhook,
  BarChart3,
  ShieldCheck,
  Zap,
  Shield,
  LineChart,
  Tags,
  Smartphone,
  Archive,
  ShieldAlert,
  Route,
  Filter,
  Facebook,
  Search,
  UserCheck,
  UsersRound,
  ThumbsUp,
  MessageCircle,
  Database,
  Share2,
  Target,
  BookOpen,
  UserRoundCog,
  Boxes,
} from "lucide-vue-next";
import type { Component } from "vue";

export interface NavItem {
  name: string;
  path: string;
  icon: Component;
  permission?: string;
  adminOnly?: boolean;
  managerOrAdminOnly?: boolean;
  childPermissions?: string[];
  children?: NavItem[];
  activeMatchPaths?: string[];
  /** When set, the subheader label renders as a clickable link to this URL. Use a relative path like "/whatsapp" so it works on any domain. */
  externalUrl?: string;
}

export const navigationItems: NavItem[] = [
  {
    name: "nav.dashboard",
    path: "/dashboard",
    icon: LayoutDashboard,
    permission: "analytics",
  },
  {
    name: "nav.chat",
    path: "/chat",
    icon: MessageSquare,
    permission: "chat",
  },
  {
    name: "nav.agentAnalytics",
    path: "/analytics/agents",
    icon: BarChart3,
    permission: "analytics.agents",
  },
  {
    name: "nav.metaInsights",
    path: "/analytics/meta-insights",
    icon: LineChart,
    permission: "analytics",
  },
  {
    name: "nav.templates",
    path: "/templates",
    icon: FileText,
    permission: "templates",
  },
  {
    name: "nav.flows",
    path: "/flows",
    icon: Workflow,
    permission: "flows.whatsapp",
  },
  {
    name: "nav.chatbot",
    path: "/chatbot",
    icon: Bot,
    permission: "settings.chatbot",
    activeMatchPaths: [
      "/chatbot",
    ],
    childPermissions: [
      "settings.chatbot",
      "chatbot.keywords",
      "flows.chatbot",
      "chatbot.ai",
      "transfers",
    ],
    children: [
      {
        name: "nav.overview",
        path: "/chatbot",
        icon: Bot,
        permission: "settings.chatbot",
      },
      {
        name: "nav.keywords",
        path: "/chatbot/keywords",
        icon: Key,
        permission: "chatbot.keywords",
      },
      {
        name: "nav.flows",
        path: "/chatbot/flows",
        icon: Workflow,
        permission: "flows.chatbot",
      },
      {
        name: "nav.aiContexts",
        path: "/chatbot/ai",
        icon: Sparkles,
        permission: "chatbot.ai",
      },
      {
        name: "nav.transfers",
        path: "/chatbot/transfers",
        icon: UserX,
        permission: "transfers",
      },
    ],
  },
  {
    name: "nav.whatsappTools",
    path: "/whatsapp",
    externalUrl: "/whatsapp",
    icon: Smartphone,
    permission: "campaigns",
    activeMatchPaths: [
      "/whatsapp",
      "/whatsapp/campaigns",
      "/whatsapp/contacts",
      "/whatsapp/canned-responses",
      "/whatsapp/saved-contents",
      "/whatsapp/closed-chats",
      "/whatsapp/whatsapp-filter",
      "/whatsapp/extract",
      "/whatsapp/instances",
      "/whatsapp/agent-selection",
    ],
    childPermissions: [
      "campaigns",
      "contacts",
      "canned_responses",
      "saved_contents",
      "wa_filter",
      "chat",
      "accounts",
      "agent_selection",
    ],
    children: [
      {
        name: "nav.campaigns",
        path: "/whatsapp/campaigns",
        icon: Megaphone,
        permission: "campaigns",
      },
      {
        name: "nav.whatsappAccounts",
        path: "/whatsapp/instances",
        icon: Smartphone,
        permission: "accounts",
      },
      {
        name: "nav.contacts",
        path: "/whatsapp/contacts",
        icon: Contact,
        permission: "contacts",
      },
      {
        name: "nav.cannedResponses",
        path: "/whatsapp/canned-responses",
        icon: MessageSquareText,
        permission: "canned_responses",
      },
      {
        name: "nav.savedContents",
        path: "/whatsapp/saved-contents",
        icon: BookOpen,
        permission: "saved_contents",
      },
      {
        name: "nav.closedChats",
        path: "/whatsapp/closed-chats",
        icon: Archive,
        permission: "chat",
      },
      {
        name: "nav.whatsappFilter",
        path: "/whatsapp/whatsapp-filter",
        icon: Filter,
        permission: "wa_filter",
      },
      {
        name: "nav.groupSearch",
        path: "/whatsapp/group-search",
        icon: Users,
        permission: "campaigns",
      },
      {
        name: "nav.groupJoinCampaigns",
        path: "/whatsapp/group-join-campaigns",
        icon: Users,
        permission: "campaigns",
      },
      {
        name: "nav.groupParticipants",
        path: "/whatsapp/group-participants",
        icon: Users,
        permission: "campaigns",
      },
      {
        name: "nav.extract",
        path: "/whatsapp/extract",
        icon: MessageSquareText,
        permission: "campaigns",
      },
      {
        name: "nav.groupExtraction",
        path: "/whatsapp/group-extraction",
        icon: Users,
        permission: "campaigns",
      },
      {
        name: "nav.memberExtraction",
        path: "/whatsapp/member-extraction",
        icon: Users,
        permission: "campaigns",
      },
      {
        name: "nav.customerRouting",
        path: "/whatsapp/agent-selection",
        icon: Route,
        permission: "agent_selection",
      },
    ],
  },
  {
    name: "nav.facebookTools",
    path: "/facebook",
    externalUrl: "/facebook",
    icon: Facebook,
    activeMatchPaths: [
      "/facebook",
    ],
    children: [
      {
        name: "nav.facebookComments",
        path: "/facebook/comments",
        icon: MessageCircle,
      },
      {
        name: "nav.facebookPageSearch",
        path: "/facebook/page-search",
        icon: Search,
      },
      {
        name: "nav.facebookPeopleSearch",
        path: "/facebook/people-search",
        icon: UserCheck,
      },
      {
        name: "nav.facebookGroupSearch",
        path: "/facebook/group-search",
        icon: UsersRound,
      },
      {
        name: "nav.facebookExtractLikes",
        path: "/facebook/extract-likes",
        icon: ThumbsUp,
      },
      {
        name: "nav.facebookPageMessengers",
        path: "/facebook/page-messengers",
        icon: MessageCircle,
      },
      {
        name: "nav.facebookExtractData",
        path: "/facebook/extract-data",
        icon: Database,
      },
      {
        name: "nav.facebookAutoShare",
        path: "/facebook/auto-share",
        icon: Share2,
      },
      {
        name: "nav.facebookRetargeting",
        path: "/facebook/retargeting",
        icon: Target,
      },
      {
        name: "nav.facebookAccounts",
        path: "/facebook/accounts",
        icon: UserRoundCog,
      },
    ],
  },
  {
    name: "nav.settings",
    path: "/settings",
    externalUrl: "/settings",
    icon: Settings,
    permission: "settings.general",
    activeMatchPaths: [
      "/settings",
      "/settings/accounts",
      "/settings/tags",
      "/settings/teams",
      "/settings/users",
      "/settings/roles",
      "/settings/api-keys",
      "/settings/webhooks",
      "/settings/custom-actions",
      "/settings/sso",
      "/settings/license",
      "/settings/modules",
    ],
    childPermissions: [
      "settings.general",
      "settings.uploads_cleanup",
      "tags",
      "teams",
      "users",
      "roles",
      "api_keys",
      "webhooks",
      "custom_actions",
      "settings.sso",
      "organizations",
    ],
    children: [
      {
        name: "nav.general",
        path: "/settings",
        icon: Settings,
        permission: "settings.general",
      },
      {
        name: "nav.accounts",
        path: "/settings/accounts",
        icon: Users,
        permission: "accounts",
      },
      {
        name: "nav.tags",
        path: "/settings/tags",
        icon: Tags,
        permission: "tags",
      },
      {
        name: "nav.teams",
        path: "/settings/teams",
        icon: Users,
        permission: "teams",
      },
      {
        name: "nav.users",
        path: "/settings/users",
        icon: Users,
        permission: "users",
      },
      {
        name: "nav.roles",
        path: "/settings/roles",
        icon: Shield,
        permission: "roles",
      },
      {
        name: "nav.apiKeys",
        path: "/settings/api-keys",
        icon: Key,
        permission: "api_keys",
      },
      {
        name: "nav.webhooks",
        path: "/settings/webhooks",
        icon: Webhook,
        permission: "webhooks",
      },
      {
        name: "nav.customActions",
        path: "/settings/custom-actions",
        icon: Zap,
        permission: "custom_actions",
      },
      {
        name: "nav.sso",
        path: "/settings/sso",
        icon: ShieldCheck,
        permission: "settings.sso",
      },
      {
        name: "nav.license",
        path: "/settings/license",
        icon: ShieldAlert,
        adminOnly: true,
      },
      {
        name: "nav.modules",
        path: "/settings/modules",
        icon: Boxes,
        permission: "organizations",
      },
    ],
  },
];
