package models

import "github.com/google/uuid"

// ActivityLog stores audit trail events generated by the system and users.
type ActivityLog struct {
	BaseModel
	OrganizationID *uuid.UUID `gorm:"type:uuid;index" json:"organization_id,omitempty"`
	UserID         *uuid.UUID `gorm:"type:uuid;index" json:"user_id,omitempty"`
	Category       string     `gorm:"size:50;not null;index" json:"category"`
	EventType      string     `gorm:"size:120;not null;index" json:"event_type"`
	Action         string     `gorm:"size:120;not null" json:"action"`
	Status         string     `gorm:"size:30;not null;index" json:"status"`
	Source         string     `gorm:"size:50;not null;index" json:"source"`
	ContactID      *uuid.UUID `gorm:"type:uuid;index" json:"contact_id,omitempty"`
	MessageID      *uuid.UUID `gorm:"type:uuid;index" json:"message_id,omitempty"`
	Method         string     `gorm:"size:10" json:"method,omitempty"`
	Path           string     `gorm:"size:255" json:"path,omitempty"`
	IPAddress      string     `gorm:"size:64" json:"ip_address,omitempty"`
	UserAgent      string     `gorm:"size:512" json:"user_agent,omitempty"`
	Metadata       JSONB      `gorm:"type:jsonb;default:'{}'" json:"metadata"`
}

func (ActivityLog) TableName() string {
	return "activity_logs"
}
