#!/usr/bin/env python3
"""Generate the Facebook Comments Workflow Enhancement Plan body PDF (ReportLab)."""

import os
import sys
import hashlib

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, HRFlowable,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.platypus import SimpleDocTemplate
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: neutral | Mode: minimal | Harmony: split_complementary
# Contrast: text:bg=15.3 | accent:bg=4.49
ACCENT = colors.HexColor('#1d7794')
TEXT_PRIMARY = colors.HexColor('#1b1a18')
TEXT_MUTED = colors.HexColor('#79756e')
BG_SURFACE = colors.HexColor('#e8e5e0')
BG_PAGE = colors.HexColor('#f2f0ee')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT = colors.white
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = BG_SURFACE

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('TimesNewRoman', '/System/Library/Fonts/Supplemental/Times New Roman.ttf'))
pdfmetrics.registerFont(TTFont('Calibri', '/System/Library/Fonts/Supplemental/Arial.ttf'))
pdfmetrics.registerFont(TTFont('CalibriBold', '/System/Library/Fonts/Supplemental/Arial Bold.ttf'))
registerFontFamily('TimesNewRoman', normal='TimesNewRoman', bold='TimesNewRoman')
registerFontFamily('Calibri', normal='Calibri', bold='Calibri')
registerFontFamily('Calibri', normal='Calibri', bold='CalibriBold')

# ━━ Output paths ━━
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
BODY_PDF = os.path.join(OUTPUT_DIR, 'body.pdf')
FINAL_PDF = os.path.join(OUTPUT_DIR, 'Facebook_Comments_Workflow_Enhancement_Plan.pdf')

# ━━ Page dimensions ━━
PAGE_W, PAGE_H = A4
LEFT_M = 1.0 * inch
RIGHT_M = 1.0 * inch
TOP_M = 0.85 * inch
BOTTOM_M = 0.85 * inch
AVAIL_W = PAGE_W - LEFT_M - RIGHT_M

# ━━ Styles ━━
styles = getSampleStyleSheet()

h1_style = ParagraphStyle(
    name='H1', fontName='TimesNewRoman', fontSize=20, leading=26,
    textColor=ACCENT, spaceBefore=18, spaceAfter=10,
)
h2_style = ParagraphStyle(
    name='H2', fontName='TimesNewRoman', fontSize=15, leading=20,
    textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=8,
)
h3_style = ParagraphStyle(
    name='H3', fontName='TimesNewRoman', fontSize=12, leading=16,
    textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6,
)
body_style = ParagraphStyle(
    name='Body', fontName='TimesNewRoman', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY,
    spaceBefore=0, spaceAfter=6,
)
bullet_style = ParagraphStyle(
    name='Bullet', fontName='TimesNewRoman', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=18, bulletIndent=6,
    spaceBefore=1, spaceAfter=2,
)
code_style = ParagraphStyle(
    name='Code', fontName='Courier', fontSize=8.5, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=6, rightIndent=6,
    spaceBefore=4, spaceAfter=4,
    backColor=BG_PAGE,
)
caption_style = ParagraphStyle(
    name='Caption', fontName='TimesNewRoman', fontSize=9, leading=13,
    textColor=TEXT_MUTED, alignment=TA_CENTER,
    spaceBefore=3, spaceAfter=6,
)
callout_style = ParagraphStyle(
    name='Callout', fontName='TimesNewRoman', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    leftIndent=12, rightIndent=8,
    spaceBefore=6, spaceAfter=6,
    borderColor=ACCENT, borderWidth=0, borderPadding=6,
)

header_cell = ParagraphStyle(
    name='HeaderCell', fontName='TimesNewRoman', fontSize=10, leading=14,
    textColor=colors.white, alignment=TA_CENTER,
)
cell_style = ParagraphStyle(
    name='Cell', fontName='TimesNewRoman', fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
cell_center = ParagraphStyle(
    name='CellCenter', fontName='TimesNewRoman', fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER,
)

# ━━ TocDocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_M - BOTTOM_M) * 0.15

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def add_major_section(text, style):
    return [
        Paragraph('', style),  # CondPageBreak placeholder
        add_heading('<b>%s</b>' % text, style, level=0),
    ]

def safe_keep(elements):
    max_h = PAGE_H * 0.40
    total = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total += h
    if total <= max_h:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def make_table(data, col_widths=None):
    if col_widths is None:
        ratios = [1.0 / len(data[0])] * len(data[0])
        col_widths = [r * AVAIL_W for r in ratios]
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_ODD if i % 2 == 0 else TABLE_ROW_EVEN
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    return t

def callout_box(stat_text, label_text):
    stat_s = ParagraphStyle(
        name='StatBig', fontName='TimesNewRoman', fontSize=22,
        leading=26, textColor=ACCENT, alignment=TA_CENTER,
    )
    lbl_s = ParagraphStyle(
        name='StatLabel', fontName='TimesNewRoman', fontSize=9,
        leading=12, textColor=TEXT_MUTED, alignment=TA_CENTER,
    )
    t = Table(
        [[Paragraph('<b>%s</b>' % stat_text, stat_s)],
         [Paragraph(label_text, lbl_s)]],
        colWidths=[160], hAlign='CENTER',
    )
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), BG_SURFACE),
        ('BOX', (0, 0), (-1, -1), 1, ACCENT),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return t

# ━━ Build document ━━
doc = TocDocTemplate(
    BODY_PDF, pagesize=A4,
    leftMargin=LEFT_M, rightMargin=RIGHT_M,
    topMargin=TOP_M, bottomMargin=BOTTOM_M,
    title='Facebook Comments Workflow Enhancement Plan',
    author='Z.ai', creator='Z.ai',
    subject='Technical review and enhancement plan for /facebook/comments route in Whatomate',
)

story = []

# ── TOC ──
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle(name='TOC1', fontSize=13, leftIndent=20, fontName='TimesNewRoman', spaceBefore=6, spaceAfter=3),
    ParagraphStyle(name='TOC2', fontSize=11, leftIndent=40, fontName='TimesNewRoman', spaceBefore=2, spaceAfter=2),
]
story.append(Paragraph('<b>Table of Contents</b>', ParagraphStyle(
    name='TOCTitle', fontName='TimesNewRoman', fontSize=20, leading=26,
    textColor=ACCENT, spaceAfter=12,
)))
story.append(toc)
story.append(PageBreak())

# ═══════════════════════════════════════════════════════════
# Section 1: Executive Summary
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('1. Executive Summary', h1_style))

story.append(Paragraph(
    'This document presents a comprehensive technical review and enhancement plan for the '
    '<b>/facebook/comments</b> route in the Whatomate platform. The review was conducted using '
    'multi-tool analysis: codebase-memory-mcp for pattern discovery, Socraticode for semantic '
    'code understanding and impact analysis, and Serena for precise source-level inspection.',
    body_style
))

story.append(Spacer(1, 12))

# KPI callouts
kpi_data = [[
    callout_box('15', 'Logic Gaps Identified'),
    callout_box('8', 'Proposed Enhancements'),
    callout_box('6', 'Sequence Changes'),
    callout_box('1,680', 'Lines of Code Reviewed'),
]]
kpi_table = Table(kpi_data, colWidths=[AVAIL_W / 4] * 4, hAlign='CENTER')
kpi_table.setStyle(TableStyle([
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(kpi_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Figure 1: Review metrics at a glance.</i>', caption_style))
story.append(Spacer(1, 12))

story.append(Paragraph(
    'The analysis covers the full webhook lifecycle: Facebook Graph API ingestion, HMAC-SHA256 '
    'signature verification, comment upsert with GORM, synchronous auto-reply (comment reply + '
    'private DM), WhatsApp notification bridging, WebSocket real-time broadcasting, and frontend '
    'merge logic for live updates. Key risk areas include cross-tenant data leakage in account '
    'lookup, silent error suppression in reply operations, and behavioral inconsistencies '
    'between the webhook and sync ingestion paths.',
    body_style
))

# ═══════════════════════════════════════════════════════════
# Section 2: Current Architecture Overview
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('2. Current Architecture Overview', h1_style))

story.append(Paragraph(
    'The Facebook comments feature is implemented primarily in <b>internal/handlers/fb_comments.go</b> '
    '(approximately 1,680 lines) with supporting models in <b>internal/models/fb_comment.go</b>. '
    'The route group is registered under <b>/facebook/comments</b> in <b>cmd/whatomate/main.go</b> '
    'with CSRF exemption and rate limiting applied at the webhook endpoint.',
    body_style
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>2.1 Request Flow</b>', h2_style))
story.append(Paragraph(
    'The webhook endpoint <b>POST /facebook/comments/webhook</b> receives real-time comment events '
    'from the Facebook Graph API. The processing pipeline follows this sequence:',
    body_style
))

flow_data = [
    [Paragraph('<b>Step</b>', header_cell), Paragraph('<b>Operation</b>', header_cell),
     Paragraph('<b>Function</b>', header_cell), Paragraph('<b>Scope</b>', header_cell)],
    [Paragraph('1', cell_center), Paragraph('HMAC-SHA256 signature verification', cell_style),
     Paragraph('verifyFacebookWebhookSignature', cell_style), Paragraph('Request', cell_center)],
    [Paragraph('2', cell_center), Paragraph('Parse webhook entry and extract page ID', cell_style),
     Paragraph('ReceiveFacebookCommentsWebhook', cell_style), Paragraph('Request', cell_center)],
    [Paragraph('3', cell_center), Paragraph('Lookup Facebook account by page ID', cell_style),
     Paragraph('findFacebookAccountByPageID', cell_style), Paragraph('Unscoped', cell_center)],
    [Paragraph('4', cell_center), Paragraph('Upsert comment into database', cell_style),
     Paragraph('upsertFacebookWebhookComment', cell_style), Paragraph('Org-scoped', cell_center)],
    [Paragraph('5', cell_center), Paragraph('Evaluate auto-reply eligibility', cell_style),
     Paragraph('shouldAutoReplyFacebookComment', cell_style), Paragraph('Org-scoped', cell_center)],
    [Paragraph('6', cell_center), Paragraph('Send comment reply + private DM', cell_style),
     Paragraph('sendAndStoreFacebookCommentReply', cell_style), Paragraph('Org-scoped', cell_center)],
    [Paragraph('7', cell_center), Paragraph('Bridge notification to WhatsApp', cell_style),
     Paragraph('maybeSendWhatsAppCommentNotification', cell_style), Paragraph('Unscoped', cell_center)],
    [Paragraph('8', cell_center), Paragraph('Broadcast via WebSocket', cell_style),
     Paragraph('WSHub.Broadcast', cell_style), Paragraph('Org-scoped', cell_center)],
]
flow_table = make_table(flow_data, [0.06 * AVAIL_W, 0.36 * AVAIL_W, 0.38 * AVAIL_W, 0.20 * AVAIL_W])
story.append(Spacer(1, 10))
story.append(flow_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 1: Webhook processing pipeline sequence.</i>', caption_style))
story.append(Spacer(1, 12))

story.append(Paragraph('<b>2.2 Data Models</b>', h2_style))
story.append(Paragraph(
    'Four GORM models support the feature, all in <b>internal/models/fb_comment.go</b>:',
    body_style
))

models_data = [
    [Paragraph('<b>Model</b>', header_cell), Paragraph('<b>Purpose</b>', header_cell),
     Paragraph('<b>Key Fields</b>', header_cell)],
    [Paragraph('FacebookComment', cell_style), Paragraph('Primary comment entity', cell_style),
     Paragraph('22 fields: ID, Message, CommenterName, IsAdminReply, AutoRepliedAt, Metadata (JSONB)', cell_style)],
    [Paragraph('FacebookCommentReply', cell_style), Paragraph('Auto/manual reply records', cell_style),
     Paragraph('13 fields: GraphCommentReplyID, GraphPrivateReplyID, Status', cell_style)],
    [Paragraph('FacebookCommentSettings', cell_style), Paragraph('Org-level settings', cell_style),
     Paragraph('14 fields: AutoReplyEnabled, PrivateReplyEnabled, WhatsAppNotifyEnabled', cell_style)],
    [Paragraph('FacebookPageCommentSettings', cell_style), Paragraph('Per-page overrides', cell_style),
     Paragraph('14 fields: WhatsAppInstanceID, page-specific toggle flags', cell_style)],
]
models_table = make_table(models_data, [0.22 * AVAIL_W, 0.30 * AVAIL_W, 0.48 * AVAIL_W])
story.append(Spacer(1, 10))
story.append(models_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 2: Facebook comment data models.</i>', caption_style))
story.append(Spacer(1, 12))

# ═══════════════════════════════════════════════════════════
# Section 3: Gap Analysis
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('3. Identified Logic Gaps', h1_style))

story.append(Paragraph(
    'The following table summarizes all 15 logic gaps discovered during the review, '
    'categorized by severity and domain. Each gap maps to one or more proposed enhancements '
    'in Section 4.',
    body_style
))
story.append(Spacer(1, 10))

gaps_data = [
    [Paragraph('<b>#</b>', header_cell), Paragraph('<b>Gap</b>', header_cell),
     Paragraph('<b>Severity</b>', header_cell), Paragraph('<b>Domain</b>', header_cell),
     Paragraph('<b>Location</b>', header_cell)],
    [Paragraph('1', cell_center),
     Paragraph('Synchronous auto-reply blocks webhook response', cell_style),
     Paragraph('High', cell_center), Paragraph('Reliability', cell_center),
     Paragraph('ReceiveFacebookCommentsWebhook', cell_style)],
    [Paragraph('2', cell_center),
     Paragraph('findFacebookAccountByPageID scans all orgs unscoped', cell_style),
     Paragraph('Critical', cell_center), Paragraph('Tenancy', cell_center),
     Paragraph('findFacebookAccountByPageID', cell_style)],
    [Paragraph('3', cell_center),
     Paragraph('No deduplication guard for rapid re-ingest', cell_style),
     Paragraph('Medium', cell_center), Paragraph('Reliability', cell_center),
     Paragraph('upsertFacebookWebhookComment', cell_style)],
    [Paragraph('4', cell_center),
     Paragraph('Silent error suppression in reply DB updates', cell_style),
     Paragraph('High', cell_center), Paragraph('Observability', cell_center),
     Paragraph('sendAndStoreFacebookCommentReply', cell_style)],
    [Paragraph('5', cell_center),
     Paragraph('No retry/backoff on Facebook API failures', cell_style),
     Paragraph('Medium', cell_center), Paragraph('Reliability', cell_center),
     Paragraph('sendAndStoreFacebookCommentReply', cell_style)],
    [Paragraph('6', cell_center),
     Paragraph('sendFacebookPrivateReply fails silently', cell_style),
     Paragraph('High', cell_center), Paragraph('Observability', cell_center),
     Paragraph('sendFacebookPrivateReply', cell_style)],
    [Paragraph('7', cell_center),
     Paragraph('Sync path ignores page-level settings for auto-reply', cell_style),
     Paragraph('Medium', cell_center), Paragraph('Consistency', cell_center),
     Paragraph('syncFacebookPageComments', cell_style)],
    [Paragraph('8', cell_center),
     Paragraph('Offset-based pagination degrades at scale', cell_style),
     Paragraph('Low', cell_center), Paragraph('Performance', cell_center),
     Paragraph('ListFacebookComments', cell_style)],
    [Paragraph('9', cell_center),
     Paragraph('Unbounded reply preload in list queries', cell_style),
     Paragraph('Medium', cell_center), Paragraph('Performance', cell_center),
     Paragraph('ListFacebookComments', cell_style)],
    [Paragraph('10', cell_center),
     Paragraph('No status transition validation', cell_style),
     Paragraph('Medium', cell_center), Paragraph('Data Integrity', cell_center),
     Paragraph('UpdateFacebookCommentStatus', cell_style)],
    [Paragraph('11', cell_center),
     Paragraph('WhatsApp bridge uses a.DB unscoped', cell_style),
     Paragraph('High', cell_center), Paragraph('Tenancy', cell_center),
     Paragraph('maybeSendWhatsAppCommentNotification', cell_style)],
    [Paragraph('12', cell_center),
     Paragraph('ReplyFacebookComment uses a.DB not requestDB', cell_style),
     Paragraph('High', cell_center), Paragraph('Tenancy', cell_center),
     Paragraph('ReplyFacebookComment', cell_style)],
    [Paragraph('13', cell_center),
     Paragraph('pickRandomReplyText has no test coverage', cell_style),
     Paragraph('Low', cell_center), Paragraph('Testing', cell_center),
     Paragraph('pickRandomReplyText', cell_style)],
    [Paragraph('14', cell_center),
     Paragraph('Webhook verifies but responds 200 even on AppSecret empty', cell_style),
     Paragraph('Medium', cell_center), Paragraph('Security', cell_center),
     Paragraph('verifyFacebookWebhookSignature', cell_style)],
    [Paragraph('15', cell_center),
     Paragraph('Frontend merge logic lacks conflict resolution', cell_style),
     Paragraph('Low', cell_center), Paragraph('Frontend', cell_center),
     Paragraph('facebookCommentsMerge.ts', cell_style)],
]

# Split into two smaller tables for readability
gaps_table1 = make_table(gaps_data[:8], [0.04 * AVAIL_W, 0.38 * AVAIL_W, 0.12 * AVAIL_W, 0.16 * AVAIL_W, 0.30 * AVAIL_W])
gaps_table2 = make_table(gaps_data[0:1] + gaps_data[8:], [0.04 * AVAIL_W, 0.38 * AVAIL_W, 0.12 * AVAIL_W, 0.16 * AVAIL_W, 0.30 * AVAIL_W])

story.append(gaps_table1)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 3: Logic gaps 1-7 (critical and high severity focus).</i>', caption_style))
story.append(Spacer(1, 14))

story.append(gaps_table2)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 4: Logic gaps 8-15 (performance, consistency, and frontend).</i>', caption_style))
story.append(Spacer(1, 12))

# ═══════════════════════════════════════════════════════════
# Section 4: Proposed Workflow Enhancements
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('4. Proposed Workflow Enhancements', h1_style))

story.append(Paragraph(
    'Eight targeted enhancements are proposed to address the identified gaps. Each enhancement '
    'is designed to be backward-compatible and can be implemented incrementally. They are '
    'prioritized by blast radius: tenancy fixes first, then reliability, then performance.',
    body_style
))

# Enhancement 1
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.1 Enhancement 1: Async Auto-Reply via Queue Worker</b>', h2_style, level=1))
story.append(Paragraph(
    'Move auto-reply logic from the synchronous webhook handler to an async Redis Streams worker. '
    'This directly addresses <b>Gap 1</b> (blocked webhook response) and <b>Gap 5</b> (no retry '
    'mechanism). The webhook handler will enqueue a job and return immediately, while the worker '
    'processes replies with exponential backoff.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph('<b>Sequence change:</b>', body_style))
story.append(Paragraph(
    'Current: webhook -> upsert -> auto-reply (sync) -> respond 200',
    bullet_style
))
story.append(Paragraph(
    'Proposed: webhook -> upsert -> enqueue job -> respond 200; worker -> dequeue -> auto-reply (with retry)',
    bullet_style
))
story.append(Spacer(1, 4))
story.append(Paragraph('<b>Addresses:</b> Gap 1, Gap 5', body_style))
story.append(Paragraph('<b>Priority:</b> High (webhook latency and reliability)', body_style))

# Enhancement 2
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.2 Enhancement 2: Tenant-Scoped Page-to-Account Lookup</b>', h2_style, level=1))
story.append(Paragraph(
    'Add an org-scoped uniqueness constraint on page-to-account mapping in '
    '<b>findFacebookAccountByPageID</b>. Currently the function scans ALL active OAuth accounts '
    'across all organizations, creating a cross-tenant data leakage risk. The fix adds a Redis '
    'cache with org-prefixed keys and restricts DB queries to the identified tenant scope.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    'Additionally, a database unique index on (organization_id, facebook_page_id) should be added '
    'to prevent duplicate page registrations across tenants.',
    bullet_style
))
story.append(Paragraph('<b>Addresses:</b> Gap 2', body_style))
story.append(Paragraph('<b>Priority:</b> Critical (multi-tenant security boundary)', body_style))

# Enhancement 3
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.3 Enhancement 3: Unified Auto-Reply Settings Resolution</b>', h2_style, level=1))
story.append(Paragraph(
    'Unify the auto-reply decision logic between <b>syncFacebookPageComments</b> (sync path) and '
    '<b>ReceiveFacebookCommentsWebhook</b> (webhook path). Currently the sync path checks only '
    'org-level settings and ignores per-page overrides, creating behavioral inconsistency. Both '
    'paths should use a shared <b>resolveAutoReplySettings()</b> helper that applies page-level '
    'overrides on top of org-level defaults.',
    body_style
))
story.append(Paragraph('<b>Addresses:</b> Gap 7', body_style))
story.append(Paragraph('<b>Priority:</b> Medium (behavioral consistency)', body_style))

# Enhancement 4
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.4 Enhancement 4: Error Logging for Silent Failures</b>', h2_style, level=1))
story.append(Paragraph(
    'Replace all silent error suppression patterns (<font name="Courier">_ = db.Updates(...).Error</font>) '
    'with explicit error logging via <font name="Courier">slog.Error</font>. This affects '
    '<b>sendAndStoreFacebookCommentReply</b> (Gap 4) and <b>sendFacebookPrivateReply</b> (Gap 6). '
    'Errors should be logged with structured context: org_id, comment_id, page_id, and the specific '
    'operation that failed.',
    body_style
))
story.append(Paragraph('<b>Addresses:</b> Gap 4, Gap 6', body_style))
story.append(Paragraph('<b>Priority:</b> High (operational visibility)', body_style))

# Enhancement 5
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.5 Enhancement 5: Tenant Scope All Direct DB Access</b>', h2_style, level=1))
story.append(Paragraph(
    'Replace all direct <font name="Courier">a.DB</font> usage with <font name="Courier">a.requestDB(rc)</font> '
    'or <font name="Courier">tenant.ScopedDB()</font> in the following handlers: '
    '<b>ReplyFacebookComment</b> (Gap 12), <b>maybeSendWhatsAppCommentNotification</b> (Gap 11). '
    'These bypass the multi-tenant boundary and could expose data across organizations.',
    body_style
))
story.append(Paragraph('<b>Addresses:</b> Gap 11, Gap 12', body_style))
story.append(Paragraph('<b>Priority:</b> Critical (multi-tenant data isolation)', body_style))

# Enhancement 6
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.6 Enhancement 6: Cursor-Based Pagination and Bounded Replies</b>', h2_style, level=1))
story.append(Paragraph(
    'Replace offset-based pagination in <b>ListFacebookComments</b> with cursor-based pagination '
    '(using comment ID or created_at as cursor) for stable results at scale (Gap 8). Add a '
    '<font name="Courier">LIMIT</font> on the reply preload clause to prevent unbounded '
    'N+1 queries (Gap 9). A maximum of 50 replies per comment should be preloaded, with a '
    'separate endpoint for full reply history.',
    body_style
))
story.append(Paragraph('<b>Addresses:</b> Gap 8, Gap 9', body_style))
story.append(Paragraph('<b>Priority:</b> Low (performance at scale)', body_style))

# Enhancement 7
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.7 Enhancement 7: Status Transition Validation</b>', h2_style, level=1))
story.append(Paragraph(
    'Add a finite state machine for comment status transitions in <b>UpdateFacebookCommentStatus</b>. '
    'Valid transitions should be defined (e.g., new -> open -> resolved -> closed) and the handler '
    'should reject invalid transitions with a clear error message. This prevents data integrity '
    'issues where comments skip states or revert from terminal states.',
    body_style
))
story.append(Paragraph('<b>Addresses:</b> Gap 10', body_style))
story.append(Paragraph('<b>Priority:</b> Medium (data integrity)', body_style))

# Enhancement 8
story.append(Spacer(1, 8))
story.append(add_heading('<b>4.8 Enhancement 8: Frontend Conflict Resolution</b>', h2_style, level=1))
story.append(Paragraph(
    'Enhance the WebSocket merge logic in <b>facebookCommentsMerge.ts</b> with last-write-wins '
    'conflict resolution based on updated_at timestamps. When a WebSocket update arrives for a '
    'comment currently being edited by the user, show a visual indicator that the comment has '
    'been modified externally. This addresses <b>Gap 15</b> (no conflict resolution in merge).',
    body_style
))
story.append(Paragraph('<b>Addresses:</b> Gap 15', body_style))
story.append(Paragraph('<b>Priority:</b> Low (user experience)', body_style))

# ═══════════════════════════════════════════════════════════
# Section 5: Gap-to-Enhancement Mapping
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('5. Gap-to-Enhancement Mapping', h1_style))

story.append(Paragraph(
    'The following matrix maps each identified gap to its corresponding enhancement(s), '
    'providing full traceability from problem to solution.',
    body_style
))
story.append(Spacer(1, 10))

map_data = [
    [Paragraph('<b>Gap</b>', header_cell), Paragraph('<b>Description</b>', header_cell),
     Paragraph('<b>Enhancement</b>', header_cell)],
    [Paragraph('1', cell_center), Paragraph('Sync auto-reply blocks webhook', cell_style),
     Paragraph('4.1 Async Auto-Reply', cell_style)],
    [Paragraph('2', cell_center), Paragraph('Unscoped account lookup', cell_style),
     Paragraph('4.2 Tenant-Scoped Lookup', cell_style)],
    [Paragraph('3', cell_center), Paragraph('No dedup on rapid re-ingest', cell_style),
     Paragraph('4.1 (idempotency in queue)', cell_style)],
    [Paragraph('4', cell_center), Paragraph('Silent DB error suppression', cell_style),
     Paragraph('4.4 Error Logging', cell_style)],
    [Paragraph('5', cell_center), Paragraph('No retry on API failure', cell_style),
     Paragraph('4.1 Async Auto-Reply', cell_style)],
    [Paragraph('6', cell_center), Paragraph('Silent private reply failure', cell_style),
     Paragraph('4.4 Error Logging', cell_style)],
    [Paragraph('7', cell_center), Paragraph('Sync ignores page settings', cell_style),
     Paragraph('4.3 Unified Settings', cell_style)],
    [Paragraph('8', cell_center), Paragraph('Offset pagination degrades', cell_style),
     Paragraph('4.6 Cursor Pagination', cell_style)],
    [Paragraph('9', cell_center), Paragraph('Unbounded reply preload', cell_style),
     Paragraph('4.6 Bounded Replies', cell_style)],
    [Paragraph('10', cell_center), Paragraph('No status validation', cell_style),
     Paragraph('4.7 Status FSM', cell_style)],
    [Paragraph('11', cell_center), Paragraph('WhatsApp bridge unscoped', cell_style),
     Paragraph('4.5 Tenant Scope DB', cell_style)],
    [Paragraph('12', cell_center), Paragraph('Reply handler uses a.DB', cell_style),
     Paragraph('4.5 Tenant Scope DB', cell_style)],
    [Paragraph('13', cell_center), Paragraph('No test for pickRandomReplyText', cell_style),
     Paragraph('(Test coverage task)', cell_style)],
    [Paragraph('14', cell_center), Paragraph('AppSecret empty accepts webhook', cell_style),
     Paragraph('(Already fixed per memory)', cell_style)],
    [Paragraph('15', cell_center), Paragraph('No merge conflict resolution', cell_style),
     Paragraph('4.8 Frontend Conflicts', cell_style)],
]
map_table = make_table(map_data, [0.06 * AVAIL_W, 0.44 * AVAIL_W, 0.50 * AVAIL_W])
story.append(map_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 5: Complete gap-to-enhancement traceability matrix.</i>', caption_style))
story.append(Spacer(1, 12))

# ═══════════════════════════════════════════════════════════
# Section 6: Proposed Sequence Diagram
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('6. Proposed Enhanced Sequence', h1_style))

story.append(Paragraph(
    'The enhanced sequence moves auto-reply out of the synchronous webhook path and into an '
    'async worker. The webhook handler becomes faster and more resilient. The worker processes '
    'replies with built-in retry and proper error logging.',
    body_style
))
story.append(Spacer(1, 10))

# Sequence as a structured table (since we can't do actual sequence diagrams easily)
seq_data = [
    [Paragraph('<b>Actor</b>', header_cell), Paragraph('<b>Action</b>', header_cell),
     Paragraph('<b>Notes</b>', header_cell)],
    [Paragraph('Facebook API', cell_style), Paragraph('POST /webhook with comment event', cell_style),
     Paragraph('HMAC-SHA256 signed payload', cell_style)],
    [Paragraph('Webhook Handler', cell_style), Paragraph('Verify signature', cell_style),
     Paragraph('Return 401 if invalid', cell_style)],
    [Paragraph('Webhook Handler', cell_style), Paragraph('Parse entry, extract page_id', cell_style),
     Paragraph('', cell_style)],
    [Paragraph('Webhook Handler', cell_style), Paragraph('Tenant-scoped account lookup', cell_style),
     Paragraph('Enhancement 4.2: org-scoped', cell_style)],
    [Paragraph('Webhook Handler', cell_style), Paragraph('Upsert comment (org-scoped DB)', cell_style),
     Paragraph('Idempotent via ON CONFLICT', cell_style)],
    [Paragraph('Webhook Handler', cell_style), Paragraph('Enqueue auto-reply job to Redis Stream', cell_style),
     Paragraph('Enhancement 4.1: async', cell_style)],
    [Paragraph('Webhook Handler', cell_style), Paragraph('Broadcast WebSocket (TypeCreated)', cell_style),
     Paragraph('Org-scoped broadcast', cell_style)],
    [Paragraph('Webhook Handler', cell_style), Paragraph('Return HTTP 200 to Facebook', cell_style),
     Paragraph('Fast response, no blocking', cell_style)],
    [Paragraph('<b>Queue Worker</b>', cell_style), Paragraph('<b>Dequeue auto-reply job</b>', cell_style),
     Paragraph('<b>Separate goroutine</b>', cell_style)],
    [Paragraph('Queue Worker', cell_style), Paragraph('Resolve settings (org + page level)', cell_style),
     Paragraph('Enhancement 4.3: unified', cell_style)],
    [Paragraph('Queue Worker', cell_style), Paragraph('Check auto-reply eligibility', cell_style),
     Paragraph('Skip admin replies', cell_style)],
    [Paragraph('Queue Worker', cell_style), Paragraph('Send comment reply via Graph API', cell_style),
     Paragraph('With retry + backoff', cell_style)],
    [Paragraph('Queue Worker', cell_style), Paragraph('Send private DM if enabled', cell_style),
     Paragraph('Enhancement 4.4: log errors', cell_style)],
    [Paragraph('Queue Worker', cell_style), Paragraph('Store reply record (org-scoped DB)', cell_style),
     Paragraph('Enhancement 4.5: scoped', cell_style)],
    [Paragraph('Queue Worker', cell_style), Paragraph('Send WhatsApp notification if enabled', cell_style),
     Paragraph('Enhancement 4.5: scoped', cell_style)],
    [Paragraph('Queue Worker', cell_style), Paragraph('Broadcast WS (TypeReplyCreated)', cell_style),
     Paragraph('Notify frontend of reply', cell_style)],
]
seq_table = make_table(seq_data, [0.18 * AVAIL_W, 0.46 * AVAIL_W, 0.36 * AVAIL_W])
story.append(seq_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 6: Proposed enhanced processing sequence.</i>', caption_style))
story.append(Spacer(1, 12))

# ═══════════════════════════════════════════════════════════
# Section 7: Implementation Priority
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('7. Implementation Priority Order', h1_style))

story.append(Paragraph(
    'Implementations should follow the priority order below, grouped into three phases. '
    'Each phase should be fully tested and deployed before the next begins.',
    body_style
))
story.append(Spacer(1, 10))

prio_data = [
    [Paragraph('<b>Phase</b>', header_cell), Paragraph('<b>Enhancement</b>', header_cell),
     Paragraph('<b>Priority</b>', header_cell), Paragraph('<b>Rationale</b>', header_cell)],
    [Paragraph('1 - Security', cell_center),
     Paragraph('4.2 Tenant-Scoped Lookup', cell_style),
     Paragraph('Critical', cell_center),
     Paragraph('Cross-tenant data leakage risk', cell_style)],
    [Paragraph('1 - Security', cell_center),
     Paragraph('4.5 Tenant Scope DB Access', cell_style),
     Paragraph('Critical', cell_center),
     Paragraph('Multi-tenant data isolation', cell_style)],
    [Paragraph('2 - Reliability', cell_center),
     Paragraph('4.4 Error Logging', cell_style),
     Paragraph('High', cell_center),
     Paragraph('Silent failures hide bugs', cell_style)],
    [Paragraph('2 - Reliability', cell_center),
     Paragraph('4.1 Async Auto-Reply', cell_style),
     Paragraph('High', cell_center),
     Paragraph('Webhook latency + retry', cell_style)],
    [Paragraph('2 - Reliability', cell_center),
     Paragraph('4.3 Unified Settings', cell_style),
     Paragraph('Medium', cell_center),
     Paragraph('Sync/webhook consistency', cell_style)],
    [Paragraph('3 - Polish', cell_center),
     Paragraph('4.7 Status FSM', cell_style),
     Paragraph('Medium', cell_center),
     Paragraph('Data integrity guard', cell_style)],
    [Paragraph('3 - Polish', cell_center),
     Paragraph('4.6 Cursor Pagination', cell_style),
     Paragraph('Low', cell_center),
     Paragraph('Performance at scale', cell_style)],
    [Paragraph('3 - Polish', cell_center),
     Paragraph('4.8 Frontend Conflicts', cell_style),
     Paragraph('Low', cell_center),
     Paragraph('User experience', cell_style)],
]
prio_table = make_table(prio_data, [0.14 * AVAIL_W, 0.30 * AVAIL_W, 0.14 * AVAIL_W, 0.42 * AVAIL_W])
story.append(prio_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 7: Three-phase implementation priority order.</i>', caption_style))
story.append(Spacer(1, 12))

# ═══════════════════════════════════════════════════════════
# Section 8: Risk Assessment
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('8. Risk Assessment', h1_style))

story.append(Paragraph(
    'Each enhancement carries implementation risks that should be mitigated through testing and '
    'gradual rollout:',
    body_style
))
story.append(Spacer(1, 8))

story.append(Paragraph('<b>8.1 Enhancement 4.1 (Async Auto-Reply)</b>', h3_style))
story.append(Paragraph(
    'Introducing a queue worker adds infrastructure complexity. Mitigation: reuse the existing '
    'Redis Streams infrastructure in <b>internal/queue/</b>. The worker should be idempotent: '
    'if a job is processed twice (e.g., due to a consumer crash), the second attempt must not '
    'create a duplicate reply. Use the comment ID + reply text hash as a deduplication key.',
    body_style
))

story.append(Paragraph('<b>8.2 Enhancement 4.2 (Tenant-Scoped Lookup)</b>', h3_style))
story.append(Paragraph(
    'Adding org-scoping to the page lookup may break webhook processing if a page is not yet '
    'associated with any organization. Mitigation: during the transition, fall back to the '
    'current unscoped query with a loud warning log, then tighten to scoped-only after confirming '
    'all pages are registered under their correct organizations.',
    body_style
))

story.append(Paragraph('<b>8.3 Enhancement 4.5 (Tenant Scope DB)</b>', h3_style))
story.append(Paragraph(
    'Replacing <font name="Courier">a.DB</font> with scoped DB requires verifying that all '
    'pre-condition queries (like finding the comment by ID) also respect tenant scoping. Mitigation: '
    'add integration tests that verify cross-org access is denied after the change.',
    body_style
))

story.append(Paragraph('<b>8.4 Enhancement 4.6 (Cursor Pagination)</b>', h3_style))
story.append(Paragraph(
    'Changing the pagination API is a breaking frontend change. Mitigation: implement cursor '
    'pagination as a new parameter (<font name="Courier">?cursor=xxx</font>) that coexists '
    'with the existing offset parameter during a deprecation period. Update the frontend service '
    'layer to prefer cursors while maintaining backward compatibility.',
    body_style
))

# ═══════════════════════════════════════════════════════════
# Section 9: Files Affected
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('9. Files Affected by Enhancement', h1_style))

story.append(Paragraph(
    'The following table lists every file that will be modified by the proposed enhancements, '
    'along with the expected change type.',
    body_style
))
story.append(Spacer(1, 10))

files_data = [
    [Paragraph('<b>File</b>', header_cell), Paragraph('<b>Enhancement(s)</b>', header_cell),
     Paragraph('<b>Change Type</b>', header_cell)],
    [Paragraph('internal/handlers/fb_comments.go', cell_style),
     Paragraph('4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7', cell_style),
     Paragraph('Major refactor', cell_style)],
    [Paragraph('internal/models/fb_comment.go', cell_style),
     Paragraph('4.2, 4.7', cell_style),
     Paragraph('Add unique index, FSM model', cell_style)],
    [Paragraph('internal/worker/', cell_style),
     Paragraph('4.1', cell_style),
     Paragraph('New worker consumer', cell_style)],
    [Paragraph('internal/queue/', cell_style),
     Paragraph('4.1', cell_style),
     Paragraph('New stream definition', cell_style)],
    [Paragraph('frontend/src/services/facebookComments.ts', cell_style),
     Paragraph('4.6, 4.8', cell_style),
     Paragraph('Cursor pagination API', cell_style)],
    [Paragraph('frontend/src/views/facebook/facebookCommentsMerge.ts', cell_style),
     Paragraph('4.8', cell_style),
     Paragraph('Conflict resolution logic', cell_style)],
    [Paragraph('internal/handlers/fb_comments_test.go', cell_style),
     Paragraph('All', cell_style),
     Paragraph('Expanded test coverage', cell_style)],
]
files_table = make_table(files_data, [0.40 * AVAIL_W, 0.34 * AVAIL_W, 0.26 * AVAIL_W])
story.append(files_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<i>Table 8: Files affected by each enhancement.</i>', caption_style))
story.append(Spacer(1, 12))

# ═══════════════════════════════════════════════════════════
# Section 10: Conclusion
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('10. Conclusion', h1_style))

story.append(Paragraph(
    'The Facebook comments feature in Whatomate is functionally complete but harbors several '
    'critical issues around multi-tenant isolation and operational observability. The two '
    'critical-priority fixes (tenant-scoped account lookup and scoped DB access) should be '
    'addressed immediately as they represent potential cross-tenant data leakage vectors.',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'The async auto-reply enhancement (4.1) is the largest single change but provides the most '
    'operational benefit: faster webhook response times, built-in retry logic, and natural '
    'separation of concerns. It should follow the security fixes in Phase 2.',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'The remaining enhancements (cursor pagination, status FSM, frontend conflict resolution) '
    'are quality-of-life improvements that can be scheduled for a subsequent release cycle. '
    'All changes maintain backward compatibility and follow the existing plugin/extension '
    'architecture patterns established in the Whatomate codebase.',
    body_style
))

# ━━ Build ━━
doc.multiBuild(story)
print('Body PDF built:', BODY_PDF)
