"""Add agency profile

Revision ID: 232bce682fa2
Revises: 3fecca3c51e1
Create Date: 2026-05-19 23:59:30.752937+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232bce682fa2'
down_revision: Union[str, None] = '3fecca3c51e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=False),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('dashboard_title', sa.String(), nullable=False),
    sa.Column('is_whitelabeled', sa.Boolean(), nullable=False),
    sa.Column('custom_domain', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_profiles')
    # ### end Alembic commands ###
