"""Add whatsapp bridge and customer fields

Revision ID: 3fecca3c51e1
Revises: 0002_performance_indexes
Create Date: 2026-05-19 23:58:13.929534+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fecca3c51e1'
down_revision: Union[str, None] = '0002_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_bridges',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('page_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id')
    )
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'reviewer'::character varying"))
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('admin_users', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('admin_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_admin_users_is_active'), table_name='admin_users')
    op.drop_index(op.f('idx_admin_users_role'), table_name='admin_users')
    op.alter_column('audit_logs', 'admin_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_page_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_page_id'), 'audit_logs', ['page_id'], unique=False)
    op.alter_column('automation_rules', 'conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('automation_rules', 'condition_logic',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'AND'::character varying"))
    op.alter_column('automation_rules', 'action_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('automation_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('automation_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('automation_rules', 'trigger_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('automation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('automation_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_automation_rules_active_priority'), table_name='automation_rules')
    op.drop_index(op.f('idx_automation_rules_page_id'), table_name='automation_rules')
    op.create_index(op.f('ix_automation_rules_page_id'), 'automation_rules', ['page_id'], unique=False)
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('campaigns', 'target_filter',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('campaigns', 'customer_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('campaigns', 'message_ar',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('campaigns', 'message_en',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('campaigns', 'media_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('campaigns', 'total_recipients',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('campaigns', 'sent_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('campaigns', 'failed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_page_id'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_status'), table_name='campaigns')
    op.create_index(op.f('ix_campaigns_page_id'), 'campaigns', ['page_id'], unique=False)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('conversations', 'urgency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('conversations', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('conversations', 'is_shadow_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'sentiment_history',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('conversations', 'guardrail_triggered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'pii_detected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_conversations_comment_page'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_customer'), table_name='conversations', postgresql_where='(customer_id IS NOT NULL)')
    op.drop_index(op.f('idx_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_intent'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_language'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_page_id'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_page_status_created'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_sentiment'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_shadow_status'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_status'), table_name='conversations')
    op.add_column('customers', sa.Column('whatsapp_id', sa.String(), nullable=True))
    op.alter_column('customers', 'interaction_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'purchase_intent',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Low'::character varying"))
    op.alter_column('customers', 'conversion_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'prospect'::character varying"))
    op.alter_column('customers', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('customers', 'notes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('customers', 'escalation_history',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('customers', 'churn_risk',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('customers', 'churn_risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('customers', 'gdpr_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_customers_churn_risk'), table_name='customers')
    op.drop_index(op.f('idx_customers_conversion_status'), table_name='customers')
    op.drop_index(op.f('idx_customers_facebook_page'), table_name='customers')
    op.drop_index(op.f('idx_customers_instagram_page'), table_name='customers')
    op.drop_index(op.f('idx_customers_last_interaction'), table_name='customers')
    op.drop_index(op.f('idx_customers_lead_score'), table_name='customers')
    op.drop_index(op.f('idx_customers_page_churn'), table_name='customers')
    op.drop_index(op.f('idx_customers_page_conversion'), table_name='customers')
    op.drop_index(op.f('idx_customers_page_id'), table_name='customers')
    op.drop_index(op.f('idx_customers_purchase_intent'), table_name='customers')
    op.create_index(op.f('ix_customers_page_id'), 'customers', ['page_id'], unique=False)
    op.alter_column('escalations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_escalations_conversation_id'), table_name='escalations')
    op.drop_index(op.f('idx_escalations_created_at'), table_name='escalations')
    op.drop_index(op.f('idx_escalations_customer_id'), table_name='escalations')
    op.drop_index(op.f('idx_escalations_page_id'), table_name='escalations')
    op.drop_index(op.f('idx_escalations_priority'), table_name='escalations')
    op.drop_index(op.f('idx_escalations_status'), table_name='escalations')
    op.drop_index(op.f('idx_escalations_status_created'), table_name='escalations')
    op.alter_column('integration_configs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('integration_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('integration_configs', 'trigger_events',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('integration_configs', 'trigger_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('integration_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_integration_configs_active'), table_name='integration_configs')
    op.drop_index(op.f('idx_integration_configs_type'), table_name='integration_configs')
    op.alter_column('knowledge_base', 'intent_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('knowledge_base', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ar'::character varying"))
    op.alter_column('knowledge_base', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('knowledge_base', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_base', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_knowledge_base_active'), table_name='knowledge_base')
    op.drop_index(op.f('idx_knowledge_base_category'), table_name='knowledge_base')
    op.drop_index(op.f('idx_knowledge_base_language'), table_name='knowledge_base')
    op.drop_index(op.f('idx_knowledge_base_page_active'), table_name='knowledge_base', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_knowledge_base_page_id'), table_name='knowledge_base')
    op.drop_index(op.f('idx_knowledge_base_usage'), table_name='knowledge_base')
    op.create_index(op.f('ix_knowledge_base_page_id'), 'knowledge_base', ['page_id'], unique=False)
    op.drop_column('knowledge_base', 'embedding')
    op.alter_column('pages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('pages', 'auto_reply_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pages', 'shadow_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pages_is_active'), table_name='pages')
    op.drop_index(op.f('idx_pages_page_id'), table_name='pages')
    op.drop_index(op.f('idx_pages_token_status'), table_name='pages')
    op.alter_column('settings', 'confidence_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.85'))
    op.alter_column('settings', 'auto_escalate_angry',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'primary_llm_model',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'hermes'::character varying"))
    op.alter_column('settings', 'fallback_llm_model',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'gpt-4o'::character varying"))
    op.alter_column('settings', 'webhook_verify_token',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'verify_token_change_me'::character varying"))
    op.alter_column('settings', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('settings', 'rate_limit_warning_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('settings', 'default_language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ar'::character varying"))
    op.alter_column('settings', 'warmup_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'safe_reply_ar',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'شكراً لتواصلك معنا. سيتواصل معك أحد ممثلي خدمة العملاء في أقرب وقت ممكن.'::text"))
    op.alter_column('settings', 'safe_reply_en',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'Thank you for reaching out. A customer service representative will contact you shortly.'::text"))
    op.alter_column('settings', 'public_reply_message_ar',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'تم التواصل معك على الخاص'::text"))
    op.alter_column('settings', 'public_reply_message_en',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'We''ve contacted you privately'::text"))
    op.alter_column('settings', 'reply_mode',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'both'::character varying"))
    op.alter_column('settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_settings_page_id'), table_name='settings')
    op.drop_index(op.f('idx_settings_page_id_unique'), table_name='settings')
    op.create_index(op.f('ix_settings_page_id'), 'settings', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_page_id'), table_name='settings')
    op.create_index(op.f('idx_settings_page_id_unique'), 'settings', [sa.literal_column("COALESCE(page_id, '__global__'::character varying)")], unique=True)
    op.create_index(op.f('idx_settings_page_id'), 'settings', ['page_id'], unique=False)
    op.alter_column('settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('settings', 'reply_mode',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'both'::character varying"))
    op.alter_column('settings', 'public_reply_message_en',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'We''ve contacted you privately'::text"))
    op.alter_column('settings', 'public_reply_message_ar',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'تم التواصل معك على الخاص'::text"))
    op.alter_column('settings', 'safe_reply_en',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Thank you for reaching out. A customer service representative will contact you shortly.'::text"))
    op.alter_column('settings', 'safe_reply_ar',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'شكراً لتواصلك معنا. سيتواصل معك أحد ممثلي خدمة العملاء في أقرب وقت ممكن.'::text"))
    op.alter_column('settings', 'warmup_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'default_language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ar'::character varying"))
    op.alter_column('settings', 'rate_limit_warning_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('settings', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('settings', 'webhook_verify_token',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'verify_token_change_me'::character varying"))
    op.alter_column('settings', 'fallback_llm_model',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'gpt-4o'::character varying"))
    op.alter_column('settings', 'primary_llm_model',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'hermes'::character varying"))
    op.alter_column('settings', 'auto_escalate_angry',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'confidence_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.85'))
    op.create_index(op.f('idx_pages_token_status'), 'pages', ['token_status'], unique=False)
    op.create_index(op.f('idx_pages_page_id'), 'pages', ['page_id'], unique=True)
    op.create_index(op.f('idx_pages_is_active'), 'pages', ['is_active'], unique=False)
    op.alter_column('pages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pages', 'shadow_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('pages', 'auto_reply_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('knowledge_base', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_knowledge_base_page_id'), table_name='knowledge_base')
    op.create_index(op.f('idx_knowledge_base_usage'), 'knowledge_base', [sa.literal_column('usage_count DESC')], unique=False)
    op.create_index(op.f('idx_knowledge_base_page_id'), 'knowledge_base', ['page_id'], unique=False)
    op.create_index(op.f('idx_knowledge_base_page_active'), 'knowledge_base', ['page_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_knowledge_base_language'), 'knowledge_base', ['language'], unique=False)
    op.create_index(op.f('idx_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_index(op.f('idx_knowledge_base_active'), 'knowledge_base', ['is_active'], unique=False)
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_base', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_base', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_base', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('knowledge_base', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ar'::character varying"))
    op.alter_column('knowledge_base', 'intent_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.create_index(op.f('idx_integration_configs_type'), 'integration_configs', ['type'], unique=False)
    op.create_index(op.f('idx_integration_configs_active'), 'integration_configs', ['is_active'], unique=False)
    op.alter_column('integration_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_configs', 'trigger_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('integration_configs', 'trigger_events',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('integration_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('integration_configs', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_escalations_status_created'), 'escalations', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_index(op.f('idx_escalations_priority'), 'escalations', ['priority'], unique=False)
    op.create_index(op.f('idx_escalations_page_id'), 'escalations', ['page_id'], unique=False)
    op.create_index(op.f('idx_escalations_customer_id'), 'escalations', ['customer_id'], unique=False)
    op.create_index(op.f('idx_escalations_created_at'), 'escalations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_escalations_conversation_id'), 'escalations', ['conversation_id'], unique=False)
    op.alter_column('escalations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_index(op.f('ix_customers_page_id'), table_name='customers')
    op.create_index(op.f('idx_customers_purchase_intent'), 'customers', ['purchase_intent'], unique=False)
    op.create_index(op.f('idx_customers_page_id'), 'customers', ['page_id'], unique=False)
    op.create_index(op.f('idx_customers_page_conversion'), 'customers', ['page_id', 'conversion_status'], unique=False)
    op.create_index(op.f('idx_customers_page_churn'), 'customers', ['page_id', 'churn_risk'], unique=False)
    op.create_index(op.f('idx_customers_lead_score'), 'customers', [sa.literal_column('lead_score DESC')], unique=False)
    op.create_index(op.f('idx_customers_last_interaction'), 'customers', [sa.literal_column('last_interaction DESC')], unique=False)
    op.create_index(op.f('idx_customers_instagram_page'), 'customers', ['instagram_id', 'page_id'], unique=False)
    op.create_index(op.f('idx_customers_facebook_page'), 'customers', ['facebook_id', 'page_id'], unique=False)
    op.create_index(op.f('idx_customers_conversion_status'), 'customers', ['conversion_status'], unique=False)
    op.create_index(op.f('idx_customers_churn_risk'), 'customers', ['churn_risk'], unique=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'gdpr_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('customers', 'churn_risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('customers', 'churn_risk',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('customers', 'escalation_history',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('customers', 'notes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('customers', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('customers', 'conversion_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'prospect'::character varying"))
    op.alter_column('customers', 'purchase_intent',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Low'::character varying"))
    op.alter_column('customers', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'interaction_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('customers', 'whatsapp_id')
    op.create_index(op.f('idx_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('idx_conversations_shadow_status'), 'conversations', ['is_shadow_mode', 'status'], unique=False)
    op.create_index(op.f('idx_conversations_sentiment'), 'conversations', ['sentiment'], unique=False)
    op.create_index(op.f('idx_conversations_page_status_created'), 'conversations', ['page_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_conversations_page_id'), 'conversations', ['page_id'], unique=False)
    op.create_index(op.f('idx_conversations_language'), 'conversations', ['language'], unique=False)
    op.create_index(op.f('idx_conversations_intent'), 'conversations', ['intent'], unique=False)
    op.create_index(op.f('idx_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('idx_conversations_customer'), 'conversations', ['customer_id'], unique=False, postgresql_where='(customer_id IS NOT NULL)')
    op.create_index(op.f('idx_conversations_created_at'), 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_conversations_comment_page'), 'conversations', ['comment_id', 'page_id'], unique=True)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'pii_detected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'guardrail_triggered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'sentiment_history',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('conversations', 'is_shadow_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('conversations', 'urgency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_campaigns_page_id'), table_name='campaigns')
    op.create_index(op.f('idx_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('idx_campaigns_page_id'), 'campaigns', ['page_id'], unique=False)
    op.create_index(op.f('idx_campaigns_created_at'), 'campaigns', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaigns', 'failed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('campaigns', 'sent_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('campaigns', 'total_recipients',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('campaigns', 'media_urls',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('campaigns', 'message_en',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('campaigns', 'message_ar',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('campaigns', 'customer_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('campaigns', 'target_filter',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index(op.f('ix_automation_rules_page_id'), table_name='automation_rules')
    op.create_index(op.f('idx_automation_rules_page_id'), 'automation_rules', ['page_id'], unique=False)
    op.create_index(op.f('idx_automation_rules_active_priority'), 'automation_rules', ['is_active', 'priority'], unique=False)
    op.alter_column('automation_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('automation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('automation_rules', 'trigger_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('automation_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('automation_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('automation_rules', 'action_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('automation_rules', 'condition_logic',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'AND'::character varying"))
    op.alter_column('automation_rules', 'conditions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_audit_logs_page_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_page_id'), 'audit_logs', ['page_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_created'), 'audit_logs', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'admin_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.create_index(op.f('idx_admin_users_role'), 'admin_users', ['role'], unique=False)
    op.create_index(op.f('idx_admin_users_is_active'), 'admin_users', ['is_active'], unique=False)
    op.alter_column('admin_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_users', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'reviewer'::character varying"))
    op.drop_table('whatsapp_bridges')
    # ### end Alembic commands ###
