"""add_enable_private_replies

Revision ID: a59aaa8f19bb
Revises: 83936982193d
Create Date: 2026-05-20 00:20:44.023393+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59aaa8f19bb'
down_revision: Union[str, None] = '83936982193d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('whatsapp_notification_phone', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('whatsapp_notification_api_key', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('enable_private_replies', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('settings', 'warmup_mode')
    op.drop_column('settings', 'default_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('default_language', sa.VARCHAR(), server_default=sa.text("'ar'::character varying"), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('warmup_mode', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('settings', 'enable_private_replies')
    op.drop_column('settings', 'whatsapp_notification_api_key')
    op.drop_column('settings', 'whatsapp_notification_phone')
    # ### end Alembic commands ###
