"""restore_columns

Revision ID: e9a928d44816
Revises: a59aaa8f19bb
Create Date: 2026-05-20 00:21:19.983184+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a928d44816'
down_revision: Union[str, None] = 'a59aaa8f19bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('default_language', sa.String(), server_default='ar', nullable=False))
    op.add_column('settings', sa.Column('warmup_mode', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'warmup_mode')
    op.drop_column('settings', 'default_language')
    # ### end Alembic commands ###
