package handlers_test

import (
	"strings"
	"testing"

	"github.com/shridarpatil/whatomate/internal/config"
	"github.com/shridarpatil/whatomate/internal/models"
	"github.com/shridarpatil/whatomate/test/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/valyala/fasthttp"
)

// --- CreateAccount: encryption + defaulting + IsDefaultIncoming flip ---

func TestApp_CreateAccount_WebhookSecretEncryptedAtRest(t *testing.T) {
	app := newTestApp(t)
	// Set a real encryption key so Encrypt is not a no-op.
	app.Config = &config.Config{
		App: config.AppConfig{EncryptionKey: "this-is-a-32-character-test-key-XX"},
		JWT: config.JWTConfig{Secret: testutil.TestJWTSecret, AccessExpiryMins: 15, RefreshExpiryDays: 7},
	}
	org := testutil.CreateTestOrganization(t, app.DB)
	user := createAdminUser(t, app, org.ID)

	req := testutil.NewJSONRequest(t, map[string]any{
		"name":                "secure",
		"gowa_base_url":       "http://gowa.local:3000",
		"gowa_device_id":      "device-z",
		"gowa_webhook_secret": "PLAIN-SECRET",
	})
	testutil.SetAuthContext(req, org.ID, user.ID)

	require.NoError(t, app.CreateAccount(req))
	require.Equal(t, fasthttp.StatusOK, testutil.GetResponseStatusCode(req))

	var stored models.WhatsAppAccount
	require.NoError(t, app.DB.Where("gowa_device_id = ?", "device-z").First(&stored).Error)
	assert.NotEqual(t, "PLAIN-SECRET", stored.GowaWebhookSecret, "webhook secret must be encrypted at rest")
	assert.True(t, strings.HasPrefix(stored.GowaWebhookSecret, "enc:"), "stored secret should carry the enc: prefix")
}

func TestApp_CreateAccount_WebhookSecretAutoGeneratedWhenEmpty(t *testing.T) {
	app := newTestApp(t)
	org := testutil.CreateTestOrganization(t, app.DB)
	user := createAdminUser(t, app, org.ID)

	req := testutil.NewJSONRequest(t, map[string]any{
		"name":           "auto-secret",
		"gowa_base_url":  "http://gowa.local:3000",
		"gowa_device_id": "device-auto",
	})
	testutil.SetAuthContext(req, org.ID, user.ID)

	require.NoError(t, app.CreateAccount(req))
	require.Equal(t, fasthttp.StatusOK, testutil.GetResponseStatusCode(req))

	var stored models.WhatsAppAccount
	require.NoError(t, app.DB.Where("name = ?", "auto-secret").First(&stored).Error)
	assert.NotEmpty(t, stored.GowaWebhookSecret, "webhook secret must be auto-generated when not supplied")
}

func TestApp_CreateAccount_DefaultIncomingFlipsExisting(t *testing.T) {
	app := newTestApp(t)
	org := testutil.CreateTestOrganization(t, app.DB)
	user := createAdminUser(t, app, org.ID)

	// Existing default incoming.
	existing := testutil.CreateTestWhatsAppAccount(t, app.DB, org.ID)
	require.NoError(t, app.DB.Model(existing).Update("is_default_incoming", true).Error)

	req := testutil.NewJSONRequest(t, map[string]any{
		"name":                "new-default",
		"gowa_base_url":       "http://gowa.local:3000",
		"gowa_device_id":      "device-2",
		"is_default_incoming": true,
	})
	testutil.SetAuthContext(req, org.ID, user.ID)

	require.NoError(t, app.CreateAccount(req))
	require.Equal(t, fasthttp.StatusOK, testutil.GetResponseStatusCode(req))

	var prev models.WhatsAppAccount
	require.NoError(t, app.DB.Where("id = ?", existing.ID).First(&prev).Error)
	assert.False(t, prev.IsDefaultIncoming, "existing default-incoming must be unset when a new default is created")

	var fresh models.WhatsAppAccount
	require.NoError(t, app.DB.Where("name = ?", "new-default").First(&fresh).Error)
	assert.True(t, fresh.IsDefaultIncoming)
}
